[BPROC-58] Padronização de erros conhecidos: BradescoNetEmpresas
mundipagg/boleto-api pull request #222
Opened 2021-03-29 19:50 UTC by bruno-sales

# Descrição

### Tarefa [BPROC-58](https://mundipagg.atlassian.net/browse/BPROC-58) 

Neste PR estamos padronizando erros conhecidos sobre a comunicação com bancos, com a finalidade de alterarmos o retorno da API de BadRequest para BadGateway, juntamente com o erro representativo da Mundipagg e o erro do banco em si.

### Tipos de alterações

- [ ] Correção de bug 
- [ ] Nova feature 
- [X] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes

### Teste Boleto com erro conhecido no momento do registro

Para simular, basta registrar um boleto de valor diferente de 200 e 201

![image](https://user-images.githubusercontent.com/15315522/112881268-d86ba600-90a1-11eb-955b-94243ceaba58.png)

### Teste Boleto com erro desconhecido no momento do registro

Para simular, basta registrar um boleto de valor 201

![image](https://user-images.githubusercontent.com/15315522/112881391-fe914600-90a1-11eb-88d0-618fd78d20bf.png)

### Teste Boleto com sucesso no registro (sem alteração)

Para simular, basta registrar um boleto de valor 200

![image](https://user-images.githubusercontent.com/15315522/112881553-35675c00-90a2-11eb-97a4-b62dbb4d4564.png)

### Testes unitários (ongoing)

2021-03-30 15:03 UTC, leojasmim approved these changes

2021-04-13 11:32 UTC, vpecanha approved these changes

2021-04-13 11:39 UTC, vpecanha requested changes
Quando retornamos BadRequest o enconding não parece estar correto. Seria bom consertamos.

2021-04-13 11:39 UTC, vpecanha commented on bankError/bank_error.go
> +var bradescoErrorMap = map[string]string{
Na tarefa estava descrito como DoD que era para logar a equivalência porém não encontrei nada aqui referente a log.

2021-08-31 22:23 UTC, closed without merging