[BPROC-75] Novos campos Caixa - Parte 1 - Rules
mundipagg/boleto-api pull request #225
Opened 2021-04-26 22:04 UTC by leojasmim

# Descrição

### Tarefa [BPROC-75](https://mundipagg.atlassian.net/browse/BPROC-75) 

Esta tarefa teve como objetivo a ampliação da requisição de registro online de boletos para a Caixa Econômica Federal, visando oferecer para os clientes algumas funcionalidades, tais quais: pagamento de valores divergentes do título, pagamento após o vencimento, além de configuração de cobrança de juros e multas. 

O PR será dividido em 2 partes e, nessa primeira parte, tratamos da integração do campos **Rules**.

#### Principais alterações da Parte 1

- **Inclusão dos novos campos no BoletoRequest**: Foram criados novos nós para recebimento das informações na requisição. O nó _Rules_ está dentro do nó _Title_ e conterá informações sobre as **regras de pagamento sobre aquele título** através de seus campos _AcceptDivergentAmount (bool)_ que permitirá ao cliente informar se aceita valores distintos do valor do título como pagamento e _MaxDaysToPayPastDue (int)_ onde será possível informar até quantos dias após o vencimento o boleto ainda poderá ser pago.
``` JSON
  "title": {
        "..."
        "rules": {
            "acceptDivergentAmount": true,
            "maxDaysToPayPastDue": 60
        }
        "..."
    },
```
- **Criação da rota V2**: Foi criada uma nova rota (v2) para o registro do boleto, de forma que requisições com os novas campos só serão permitidas a partir dela, mantendo o contrato igual para cliente da (v1). Ainda que na rota v2, os novos campos dó serão aceitos para Caixa Econômica, e a requisição sofrerá um BadRequest caso o banco seja divergente.

- **Refatoração do Middleware**: Foram reorganizados alguns métodos do **middleware.go** visando dar maior legibilidade ao código. Segregamos a parte responsável pelo log do _Request_ e _Response_ da BoletoAPI, que agora está na função _Logger_ e a função _ParseBoleto_ é responsável apenas pelos mapeamentos da requisição. Além disso foram adicionadas função para validação das rotas V1 e V2, em função da criação dos novos campos.

- **Criação de objetos para melhorias dos testes**: Anteriormente tinhamós variável _baseMockJSON_, que era uma string JSON com o exemplo requisição que utilizávamos para o teste do método _ProcessBoleto_. Entretanto, para criar variações nesse objeto o mesmo era convertido para um objeto _BoletoRequest_ e, a partir disso, a prorpriedade era alterada:
```Golang
        input := new(models.BoletoRequest)
	util.FromJSON(baseMockJSON, input)
	input.Title.AmountInCents = 400
```
Para resolver esse problema utilizamos uma adaptação do padrão _Builder_. No pacote **test/builder** criamos o _BuilderBoletoRequest_, responsável por criar um BoletoRequest de acordo com as informações passadas. Já em **caixa/stub** criamos o _stubBoletoRequestCaixa_, no qual temos um _BoletoRequest_ default, e através dos métodos _withAmountIsCents, withOurNumber, withRecipientDocumentNumber, withAgreementNumber, withExpirationDate, withStrictRules e withFlexRules é possível customizar o BoletoRequest de acordo com o teste a ser realizado. O exemplo anterior passou a ser escrito da seguinte forma:
```Golang
       input := newStubBoletoRequestCaixa().withAmountIsCents(400).Build()
```

### Tipos de alterações

- [ ] Correção de bug 
- [x] Nova feature 
- [ ] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes

Foram criados testes unitários visando verificar se a conversão do objeto BoletoRequest para o XML da requisição da Caixa foi realizado corretamente. Além desses testes, todos os testes unitários foram executados com sucesso:

![image](https://user-images.githubusercontent.com/18493760/116154104-a197a880-a6be-11eb-88d3-a2f263193cbd.png)

Realizamos testes de integração com a API, sendo verificados os cenários descritos abaixo:

### Teste Local

#### CENÁRIO 1 - Registro de Boleto Caixa no modelo antigo na rota V1

Neste cenário verificamos a retrocompatibilidade, realizando uma requisição na rota v1 para a Caixa, sem os novos campos e podemos verificar que a transação foi processado com sucesso:

![image](https://user-images.githubusercontent.com/18493760/116154723-68136d00-a6bf-11eb-802c-b2d34d630b45.png)

#### CENÁRIO 2 - Registro de Boleto geral no modelo antigo na rota V1

Neste cenário verificamos a retrocompatibilidade, realizando uma requisição na rota v1 para outro banco, sem os novos campos. A requisição foi realizada utilizando o banco Santander e podemos verificar que a transação foi processado com sucesso:

![image](https://user-images.githubusercontent.com/18493760/116155067-fd166600-a6bf-11eb-9948-4e61fca45015.png)

#### CENÁRIO 3 - Registro de Boleto com informações de Rules na rota V1

Este cenário testa a validação realizada no middleware para a Rota v1. Tentamos fazer uma requisição passando o campo _rules_ e a requisição é devidamente bloqueada, independente do banco utilizado:

![image](https://user-images.githubusercontent.com/18493760/116155301-4e265a00-a6c0-11eb-936e-1ed081ae7c01.png)

![image](https://user-images.githubusercontent.com/18493760/116155397-69916500-a6c0-11eb-94cf-3c746cd809f9.png)

#### CENÁRIO 4 - Registro de Boleto com informações de Rules na rota V2 para bancos diversos

Este cenário testa a validação realizada no middleware para a Rota v2. Tentamos fazer uma requisição passando o campo _rules_ com um banco diferente da Caixa Econômica e a requisição é devidamente bloqueada:

![image](https://user-images.githubusercontent.com/18493760/116155655-c3922a80-a6c0-11eb-93bf-eb77f7bcbac1.png)

#### CENÁRIO 5 - Registro de Boleto com modelo restrito na rota V2

Neste cenário testamos o envio de regras mais restritas de pagamento, como não aceitar valores divergentes nem pagamento após o vencimento e o boleto é registrado com sucesso:

![image](https://user-images.githubusercontent.com/18493760/116155847-11a72e00-a6c1-11eb-9d7f-353dad4ffb49.png)

No log é possível verificar que o campo _Rules_ foi devidamente recebido e a requisição mapeada para a Caixa conforme esperado:

![image](https://user-images.githubusercontent.com/18493760/116155981-46b38080-a6c1-11eb-971b-e180228a48a4.png)

![image](https://user-images.githubusercontent.com/18493760/116156092-6cd92080-a6c1-11eb-9480-b2ba990d43de.png)

![image](https://user-images.githubusercontent.com/18493760/116156217-92662a00-a6c1-11eb-95cc-679080e4e4d9.png)

#### CENÁRIO 6 - Registro de Boleto com modelo flexivel na rota V2

Neste cenário testamos o envio de regras mais flexíveis de pagamento, como aceitar valores divergentes e pagamento até 60 dias após o vencimento e o boleto é registrado com sucesso:

![image](https://user-images.githubusercontent.com/18493760/116156394-c93c4000-a6c1-11eb-870e-4646fe8741a9.png)

No log é possível verificar que o campo _Rules_ foi devidamente recebido e a requisição mapeada para a Caixa conforme esperado:

![image](https://user-images.githubusercontent.com/18493760/116156516-f8eb4800-a6c1-11eb-9314-ae405ac3c38c.png)

![image](https://user-images.githubusercontent.com/18493760/116156558-056fa080-a6c2-11eb-8948-434d7ee67978.png)

![image](https://user-images.githubusercontent.com/18493760/116156620-1cae8e00-a6c2-11eb-8934-118bcfd96565.png)

### Teste Staging

🚧 Em andamento

## Checklist

- [ ] Associei corretamente a Tarefa do Board ao Pull Request.
- [ ] Meu código segue as diretrizes desse projeto.
- [ ] Eu revisei meu próprio código.
- [ ] Eu comentei meu código em áreas particulares de difícil compreensão.
- [ ] Eu atualizei a documentação de acordo com as mudanças realizadas.
- [ ] Meu código não gerou novos warnings.
- [ ] Eu adicionei testes que provam que minha correção é efetiva ou que a nova feature funciona.
- [ ] Testes novos e existentes passam localmente com minhas alterações. 
- [ ] Testes novos e existentes passam em staging com minhas alterações. 
- [ ] Qualquer dependência dessa alteração já foi realizada (deploy, configuração em todos os ambientes, etc).

2021-04-28 15:39 UTC, henriquefonseca commented on models/fine_test.go
> +var isValidFineParameters = []testFineParameter{
O nome da variável sugere um boolean. Que tal alterar para `FineParameters` ou `FineParametersCollection`?

2021-04-28 15:39 UTC, henriquefonseca commented on models/interest_test.go
> +var isValidInterestParameters = []testInterestParameter{
Essa variável está na mesma situação: sugere um boolean. E se alterarmos para `ValidInterestParameters`?

2021-04-28 15:39 UTC, henriquefonseca commented on models/title.go
> +	Rules          *Rules    `json:"rules,omitempty"`
Aqui você preferiu um ponteiro por algum motivo específico?

2021-04-28 15:39 UTC, henriquefonseca commented on test/builder.go
> +func (b *BuilderBoletoRequest) GetRequest() *models.BoletoRequest {
O nome do método não está errado, mas geralmente usamos sem o Get: https://golang.org/doc/effective_go#Getters

2021-04-28 17:55 UTC, leojasmim commented on api/middlewares.go
> +		checkError(c, e, log.CreateLog())
@henriquefonseca Esse pacote _metrics_ que utilizava o InfluxDb... atualmente não estamos mais utilizando ele... a ideia é futuramente utilizar o NewRelic.

2021-04-28 17:59 UTC, leojasmim commented on api/middlewares.go
> +		c.Set("error", err)
@henriquefonseca Idem ao anterior. Atualmente não recebemos mas fazemos a verificação no _middleware_ _ParseBoleto_ junto com a validação do contrato enviado.

2021-04-28 17:59 UTC, leojasmim commented on caixa/caixa_test.go
> +	input := newStubBoletoRequestCaixa().withAmountIsCents(400).Build()
😅

2021-04-28 18:01 UTC, leojasmim commented on models/fine_test.go
> +var isValidFineParameters = []testFineParameter{
👌

2021-04-28 18:02 UTC, leojasmim commented on models/interest_test.go
> +var isValidInterestParameters = []testInterestParameter{
👌

2021-04-28 18:09 UTC, leojasmim commented on models/title.go
> +	Rules          *Rules    `json:"rules,omitempty"`
@henriquefonseca Escolhi o ponteiro porque na validação das rotas preciso verificar se o objeto foi enviado ou não... Se eu utilizar a instância, por default eu terei um objeto _Rules_ prenchido com seus parâmetros default e não seria possível verificar se objeto foi enviado pelo cliente
``` Golang
models.Rules {
	AcceptDivergentAmount: false,
	MaxDaysToPayPastDue:   0,
}
```

2021-04-28 18:12 UTC, leojasmim commented on test/builder.go
> +func (b *BuilderBoletoRequest) GetRequest() *models.BoletoRequest {
👌

2021-04-28 18:13 UTC, henriquefonseca commented on models/title.go
> +	Rules          *Rules    `json:"rules,omitempty"`
Mas se ele não for enviado pelo cliente, o comportamento que teríamos não seria exatamente o mesmo do que teríamos com os valores default? Ou o campo é obrigatório e sempre precisamos receber?

2021-04-28 18:36 UTC, leojasmim commented on models/title.go
> +	Rules          *Rules    `json:"rules,omitempty"`
@henriquefonseca Não necessariamente... por exemplo... atualmente não utilizamos o nó _PAGAMENTO_ na requisição para a Caixa:

![image](https://user-images.githubusercontent.com/18493760/116455129-18f04800-a837-11eb-8076-e93061d4a9be.png)

Se eu receber o valor  `AcceptDivergentAmount=false` eu vou entender que preciso inserir esse nó informando que não aceito valores divergentes:

![image](https://user-images.githubusercontent.com/18493760/116455208-2efe0880-a837-11eb-8de6-2d3b1ac15fb1.png)

Em geral o comportamento _default_ atual é idêntico ao comportamento com o nó de _PAGAMENTO_ com o tipo _NAO_ACEITA_VALOR_DIVERGENTE_, entretanto, apenas por precaução, preferimos não alterar o contrato antigo.

Além disso, um dos requisitos era justamente validar se o campo foi enviado pela rota v1, pois nela ele não será permitido... Então eu preciso que de fato o objeto seja nulo quando não for enviado.

2021-04-28 18:46 UTC, henriquefonseca commented on models/title.go
> +	Rules          *Rules    `json:"rules,omitempty"`
Entendido. Obrigado pela explicação.

2021-04-28 18:47 UTC, henriquefonseca approved these changes

2021-04-30 17:41 UTC, leojasmim commented on test/stub_test.go
> +func Test_StubBoletoRequest_WhenCreateAndSetBoletoRequest_ReturnBoletoRequestSuccessful(t *testing.T) {
Sim...

2021-04-30 17:42 UTC, leojasmim commented on api/middlewares_test.go
> +func Test_ValidateRegisterV2_WhenWithoutRules_PassSuccessful(t *testing.T) {
Não... na V2 elas serão permitidas, caso o banco seja Caixa.

2021-04-30 18:16 UTC, henriquefonseca approved these changes

2021-05-04 21:53 UTC, vpecanha reviewed
Nas evidências do PR senti falta do cenário 2 e 4 estarem aplicados para todos os bancos diferentes de CEF e não pegar apenas um.

2021-05-04 21:53 UTC, vpecanha commented on api/routes.go
> +//V2 intala a api versao 2
```suggestion
//V2 instala a api versao 2
```

2021-05-04 21:53 UTC, vpecanha commented on models/fine.go
> +	if f.Days < 0 {
Seria bom isolar em uma constante para explicar o que significa este zero, não?

2021-05-04 21:53 UTC, vpecanha commented on models/interest_test.go
> +	{Input: Interest{Type: "Percentual", Days: 0, Rate: 0.020}, AmountInCents: 0, Expected: true},
E se adicionarmos um espaço em branco no final?

2021-05-04 21:53 UTC, vpecanha commented on api/middlewares.go
>  import (
Questionamento sincero @leojasmim e @henriquefonseca: Esse middlware não estrapolou de responsabilidade e ficou um utils genérico?

2021-05-05 12:12 UTC, leojasmim commented on api/routes.go
> +//V2 intala a api versao 2
👌

2021-05-05 12:14 UTC, leojasmim commented
> Nas evidências do PR senti falta do cenário 2 e 4 estarem aplicados para todos os bancos diferentes de CEF e não pegar apenas um.

@vpecanha Não sei se ficou claro mas foram justamente os testes realizados em staging, isto é, todos os bancos na rota v1 e todos os bancos na rota v2.

2021-05-05 12:21 UTC, leojasmim commented on models/fine.go
> +	if f.Days < 0 {
👌

2021-05-05 12:22 UTC, leojasmim commented on models/interest_test.go
> +	{Input: Interest{Type: "Percentual", Days: 0, Rate: 0.020}, AmountInCents: 0, Expected: true},
@vpecanha no final do Type? Vai dar erro

2021-05-05 12:26 UTC, leojasmim commented on api/middlewares.go
>  import (
@vpecanha Tem algumas extrações para deixar a leitura das funções principais do middleware mais legíveis... Se vc quiser coloco essas funções em um arquivo _util.go_

2021-05-05 14:06 UTC, leojasmim commented
Aproveitamos para corrigir o problema do erro no mapeamento de caracteres para requisição da Caixa. A definição dos caracteres aceitos encontra-se na pagina 8 da documentação da Caixa e, quando não corresponder à um caracter aceito o mesmo será substituído por espaço em branco, conforme preconizado na documentação:

![image](https://user-images.githubusercontent.com/18493760/117153815-b4327180-ad91-11eb-91ea-37d4e43a366a.png)

2021-05-05 14:34 UTC, henriquefonseca commented on api/middlewares.go
>  import (
Acho que é um bom ponto, @vpecanha . Daria sim, para distribuir estas funções em diferentes responsabilidades.
Não gosto muito da ideia do "util.go", @leojasmim . 
Tem muita "cara de Java" (nada contra... só não é Go) e vai contra a convenção de nomenclatura da linguagem, que busca nomes mais concisos e descritivos, ao invés de generalismos ou nomes enigmáticos.
Talvez uma ideia a se considerar seria extrair esse arquivo desse pacote e criar um `package middleware`, por exemplo. 
E dentro dele agrupar estas funções em arquivos com nomes relacionados às responsabilidades. Poderia ter um "authentication.go" e um "parser.go".

Ao usar teríamos algo como:
```
middlewares.authentication()
```
ou
```
middlewares.parseBoleto()
```
Que tal?

2021-05-05 20:51 UTC, vpecanha commented on api/middlewares.go
>  import (
Acho que vale debatermos, adicionar tarefa de melhoria e pegarmos quando mexermos na boleto-api novamente @henriquefonseca @leojasmim

2021-05-05 21:06 UTC, vpecanha requested changes
Muito foda! Vi aqui eu vocês adicionaram a correção do enconding da CEF 😄 !

Como o time de produtos não definiu tarefa nem casos de testes então não podemos seguir com o deploy 😞

2021-05-05 23:19 UTC, leojasmim commented
> Muito foda! Vi aqui eu vocês adicionaram a correção do enconding da CEF 😄 !
> 
> Como o time de produtos não definiu tarefa nem casos de testes então não podemos seguir com o deploy 😞

@vpecanha Dei revert na alteração mas deixei ela na branch [fix/characters-caixa](https://github.com/mundipagg/boleto-api/tree/fix/characters-caixa)

2021-06-25 18:10 UTC, leojasmim commented
PR reaberto https://github.com/mundipagg/boleto-api/pull/240

2021-06-25 18:10 UTC, closed without merging