[BPRC-137][Fix] Returning the created mongo connection instead create a new one
mundipagg/boleto-api pull request #239
Opened 2021-06-23 15:15 UTC by henriquefonseca

# Descrição

### Tarefa [BPROC-137](https://mundipagg.atlassian.net/browse/BPROC-137) 

Identificamos que a cada request, a connection com o mongo está sendo recriada. Este é um fix que força o uso da variável de pacote **conn**, em **db**, impedindo a criação de novas connections a cada nova requisição.

### Tipos de alterações

- [x] Correção de bug 
- [ ] Nova feature 
- [ ] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes
### Testes Unitários

## Checklist

- [ ] Associei corretamente a Tarefa do Board ao Pull Request.
- [ ] Meu código segue as diretrizes desse projeto.
- [ ] Eu revisei meu próprio código.
- [ ] Eu comentei meu código em áreas particulares de difícil compreensão.
- [ ] Eu atualizei a documentação de acordo com as mudanças realizadas.
- [ ] Meu código não gerou novos warnings.
- [ ] Eu adicionei testes que provam que minha correção é efetiva ou que a nova feature funciona.
- [ ] Testes novos e existentes passam localmente com minhas alterações. 
- [ ] Testes novos e existentes passam em staging com minhas alterações. 
- [ ] Qualquer dependência dessa alteração já foi realizada (deploy, configuração em todos os ambientes, etc).

2021-06-23 20:18 UTC, leojasmim approved these changes

2021-06-23 22:02 UTC, vpecanha requested changes
Não há evidências de que o problema de estouro de recursos foi sanado.

2021-06-24 21:39 UTC, wesleycosta approved these changes

2021-06-25 13:31 UTC, leojasmim commented
@vpecanha Realizamos um teste mais extensivo no ambiente de Staging, conforme descrito abaixo:

### Metodologia do Teste

- **Objetivo**: Observar o comportamento das métricas de _runtime_ da aplicação (CPU, memória, Go Routines) quando a aplicação é submetida a requisições constantes em seus endpoints que tem interação com o MongoDB, i.e., **register** e **get**.
- **Ambiente**: Staging
- **Pré-Requisitos**: 
  - Newman;
  - Json da collection Postman  _**BoletoAPI - All Requests**_;
  - Json do environment _**BoletoAPI Staging**_
  - NewRelic habilitado no ambiente de Staging;
- **Método**: Realizar 500 iterações, consecutivas, da pasta _Route V1_ presente na collection. Essa pasta contém 08 requisições de registro de boleto (01 para cada banco); 08 requisições de busca de boleto em formato html (01 para cada banco) e 08 requisições de busca de boleto em formato pdf (01 para cada banco). Cabe ressaltar que as requisições de busca de boleto realizam previamente seu registro, logo perfazemos o total de 40 requisições a cada iteração da pasta _Route V1_ e assim 20.000 requisições ao final do teste. 
- **Resultado esperado**: Que as métricas se mantenham constantes durante o teste.
- **Início**: 24/06/2021 às 20:06h
- **Término**: 25/06/2021 às 04:25h

#### Observações

Inicialmente fizemos redeploy da aplicação com o fix no ambiente de staging às 20:06h:

![image](https://user-images.githubusercontent.com/18493760/123428911-b3051000-d59c-11eb-84c4-34698ffe6801.png)

![image](https://user-images.githubusercontent.com/18493760/123428937-b8625a80-d59c-11eb-8098-da154de11008.png)

Foram realizadas 02 tentativas de teste através do Postman, porém o mesmo estava sendo reiniciado por consumir muito recurso da máquina solicitante então foi necessário fazer uso do pacote Newman para realizar as requisições. Fizemos então a exportação do _json_ da _collection_ e do _environment_. 

Iniciamos os testes através do Newman às 21:45h do dia 24:

![image](https://user-images.githubusercontent.com/18493760/123429356-3fafce00-d59d-11eb-8913-4bdd3327d654.png)

Ao final do teste verificamos que 09% dos _assertions_ falharam em função de bloqueio da CloudFlare (HttpStatusCode 429):

![image](https://user-images.githubusercontent.com/18493760/123429881-de3c2f00-d59d-11eb-9b40-6d3591f58646.png)

Mesmo assim foi possível verificar que a métricas mantiveram-se constantes durante o processo com os seguintes números:
- CPU: < 2,5%
- GoRoutines: < 30
- Memória: < 08 MB

![image](https://user-images.githubusercontent.com/18493760/123430230-50ad0f00-d59e-11eb-95ce-f7ef91c2313d.png)

No dia do incidente percebemos que houve um comportamento linear ao longo tempo:

![image](https://user-images.githubusercontent.com/18493760/123431916-2e1bf580-d5a0-11eb-9aa4-d80c8ff1ef72.png)

Desta forma, por ter apresentado com comportamento constante durante todo período do teste, a correção aqui apresentada o resolve o problema identificado.

2021-06-28 13:01 UTC, vpecanha approved these changes
Evidências satisfatórias

2021-06-30 11:07 UTC, merged