Feature/bproc 75 novos campos caixa v2
mundipagg/boleto-api pull request #240
Opened 2021-06-25 17:51 UTC by leojasmim

# Descrição

### Tarefa [BPROC-75](https://mundipagg.atlassian.net/browse/BPROC-75) 

Esta tarefa teve como objetivo a ampliação da requisição de registro online de boletos para a Caixa Econômica Federal, visando oferecer para os clientes algumas funcionalidades, tais quais: pagamento de valores divergentes do título, pagamento após o vencimento, além de configuração de cobrança de juros e multas. 

O PR será dividido em 2 partes e, nessa primeira parte, tratamos da integração do campos **Rules**.

#### Principais alterações da Parte 1

- **Inclusão dos novos campos no BoletoRequest**: Foram criados novos nós para recebimento das informações na requisição. O nó _Rules_ está dentro do nó _Title_ e conterá informações sobre as **regras de pagamento sobre aquele título** através de seus campos _AcceptDivergentAmount (bool)_ que permitirá ao cliente informar se aceita valores distintos do valor do título como pagamento e _MaxDaysToPayPastDue (int)_ onde será possível informar até quantos dias após o vencimento o boleto ainda poderá ser pago.
``` JSON
  "title": {
        "..."
        "rules": {
            "acceptDivergentAmount": true,
            "maxDaysToPayPastDue": 60
        }
        "..."
    },
```
- **Criação da rota V2**: Foi criada uma nova rota (v2) para o registro do boleto, de forma que requisições com os novas campos só serão permitidas a partir dela, mantendo o contrato igual para cliente da (v1). Ainda que na rota v2, os novos campos dó serão aceitos para Caixa Econômica, e a requisição sofrerá um BadRequest caso o banco seja divergente.

- **Refatoração do Middleware**: Foram reorganizados alguns métodos do **middleware.go** visando dar maior legibilidade ao código. Segregamos a parte responsável pelo log do _Request_ e _Response_ da BoletoAPI, que agora está na função _Logger_ e a função _ParseBoleto_ é responsável apenas pelos mapeamentos da requisição. Além disso foram adicionadas função para validação das rotas V1 e V2, em função da criação dos novos campos. Foram adicionados testes para esta camada.

- **Criação de objetos para melhorias dos testes**: Anteriormente tinhamós variável _baseMockJSON_, que era uma string JSON com o exemplo requisição que utilizávamos para o teste do método _ProcessBoleto_. Entretanto, para criar variações nesse objeto o mesmo era convertido para um objeto _BoletoRequest_ e, a partir disso, a prorpriedade era alterada:
```Golang
        input := new(models.BoletoRequest)
	util.FromJSON(baseMockJSON, input)
	input.Title.AmountInCents = 400
```
Para resolver esse problema utilizamos uma adaptação do padrão [_Builder_](https://golangbyexample.com/builder-pattern-golang/). No pacote **test/builder** criamos o _BuilderBoletoRequest_, responsável por criar um BoletoRequest de acordo com as informações passadas. Além disso criamos um objeto _StubBoletoRequest_ que serve como base para criação de novos _stubs_ específicos de cada banco, no qual temos um _BoletoRequest_ vazio, e através dos métodos _WithAmountIsCents, WithOurNumber, WithRecipientDocumentNumber, WithAgreementNumber, WithExpirationDate e WithRules, é possível customizar o BoletoRequest de acordo com o teste a ser realizado. Já em **caixa/stub** criamos o _stubBoletoRequestCaixa_, que possuí um _StubBoletoRequest_  embutido e adiciona as funções withStrictRules e withFlexRules, de forma a permitir testar a rota V2. O exemplo anterior passou a ser escrito da seguinte forma:

```Golang
       input := newStubBoletoRequestCaixa().withAmountIsCents(400).Build()
```

### Tipos de alterações

- [ ] Correção de bug 
- [x] Nova feature 
- [ ] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes

Foram criados testes unitários visando verificar se a conversão do objeto BoletoRequest para o XML da requisição da Caixa foi realizado corretamente. Além desses testes, todos os testes unitários foram executados com sucesso:

![image](https://user-images.githubusercontent.com/18493760/123460559-3420cf00-d5be-11eb-8b78-2b0d260fc8d1.png)

Executamos os testes da collection **BoletoAPI - All Requests**, já atualizados com a rota V2:

![image](https://user-images.githubusercontent.com/18493760/123465652-c4621280-d5c4-11eb-81bb-e87528363daf.png)

Realizamos testes de integração com a API, com a collection **#BPROC - 75 - BOLETOAPI - Rules e Fees**, sendo verificados os cenários descritos abaixo:

### Teste Local

#### CENÁRIO 1 - Registro de Boleto Caixa no modelo antigo na rota V1

Neste cenário verificamos a retrocompatibilidade, realizando uma requisição na rota v1 para a Caixa, sem os novos campos e podemos verificar que a transação foi processado com sucesso:

![image](https://user-images.githubusercontent.com/18493760/123460755-7f3ae200-d5be-11eb-92df-e3357e556a02.png)

#### CENÁRIO 2 - Registro de Boleto geral no modelo antigo na rota V1

Neste cenário verificamos a retrocompatibilidade, realizando uma requisição na rota v1 para outro banco, sem os novos campos. A requisição foi realizada utilizando o banco Santander e podemos verificar que a transação foi processado com sucesso:

![image](https://user-images.githubusercontent.com/18493760/123460814-97aafc80-d5be-11eb-9667-e04dc1a7cb94.png)

#### CENÁRIO 3 - Registro de Boleto com informações de Rules na rota V1

Este cenário testa a validação realizada no middleware para a Rota v1. Tentamos fazer uma requisição passando o campo _rules_ e a requisição é devidamente bloqueada, independente do banco utilizado:

![image](https://user-images.githubusercontent.com/18493760/123460931-c6c16e00-d5be-11eb-9de5-092ee73245b6.png)

![image](https://user-images.githubusercontent.com/18493760/123460982-d640b700-d5be-11eb-8d0e-a774d54b5605.png)

#### CENÁRIO 4 - Registro de Boleto com informações de Rules na rota V2 para bancos diversos

Este cenário testa a validação realizada no middleware para a Rota v2. Tentamos fazer uma requisição passando o campo _rules_ com um banco diferente da Caixa Econômica e a requisição é devidamente bloqueada:

![image](https://user-images.githubusercontent.com/18493760/123462669-f96c6600-d5c0-11eb-8af7-e411541ba573.png)

#### CENÁRIO 5 - Registro de Boleto com modelo restrito na rota V2

Neste cenário testamos o envio de regras mais restritas de pagamento, como não aceitar valores divergentes nem pagamento após o vencimento e o boleto é registrado com sucesso:

![image](https://user-images.githubusercontent.com/18493760/123463032-6aac1900-d5c1-11eb-9114-cce5b6bb4eb9.png)

No log é possível verificar que o campo _Rules_ foi devidamente recebido e a requisição mapeada para a Caixa conforme esperado:

![image](https://user-images.githubusercontent.com/18493760/123464178-df338780-d5c2-11eb-8219-9f8dee9547e7.png)

![image](https://user-images.githubusercontent.com/18493760/123464318-0ab67200-d5c3-11eb-99bb-265269c3e99f.png)

![image](https://user-images.githubusercontent.com/18493760/123464410-228df600-d5c3-11eb-9e04-44845e3e1e48.png)

#### CENÁRIO 6 - Registro de Boleto com modelo flexivel na rota V2

Neste cenário testamos o envio de regras mais flexíveis de pagamento, como aceitar valores divergentes e pagamento até 60 dias após o vencimento e o boleto é registrado com sucesso:

![image](https://user-images.githubusercontent.com/18493760/123464558-59640c00-d5c3-11eb-9741-d131524e6071.png)

No log é possível verificar que o campo _Rules_ foi devidamente recebido e a requisição mapeada para a Caixa conforme esperado:

![image](https://user-images.githubusercontent.com/18493760/123464708-8dd7c800-d5c3-11eb-9ef1-6b862dfb9411.png)

![image](https://user-images.githubusercontent.com/18493760/123464787-a9db6980-d5c3-11eb-86d7-38bf86e10886.png)

![image](https://user-images.githubusercontent.com/18493760/123464865-bf509380-d5c3-11eb-9078-8c9c8befc439.png)

#### CENÁRIO 7 - Get Boleto gerado com modelo restrito

Neste cenário testamos a visualização do boleto criado pelo rota V2 com modelo restrito

![image](https://user-images.githubusercontent.com/18493760/1 [...]

2021-06-28 14:41 UTC, wesleycosta commented on models/rules.go
> +	AcceptDivergentAmount bool `json:"acceptDivergentAmount"`
Como o deploy desse PR está agendado para quarta-feira (30/06/21), e deploy do novo ORM para quinta-feira (01/07/21).
Será necessário abrir um PR com o revert do novo ORM, certo?
Já que o PR do novo ORM já foi "mergeado" e depois rolou o rollback da versão.

2021-06-28 14:46 UTC, leojasmim commented on models/rules.go
> +	AcceptDivergentAmount bool `json:"acceptDivergentAmount"`
O ideal é subir esse após o do hotfix

2021-06-28 14:51 UTC, wesleycosta commented on models/rules.go
> +	AcceptDivergentAmount bool `json:"acceptDivergentAmount"`
Boa Terê! Essa dúvida surgiu por causa da sequência de deploy enviado pelo @vpecanha.
Uma sugestão seria inverter o deploy do pagamento restritivo com o fix do novo ORM, o que acham?

![image](https://user-images.githubusercontent.com/3426975/123657434-28741900-d807-11eb-9bc5-1ae7a3e41460.png)

2021-06-28 15:55 UTC, wesleycosta approved these changes

2021-06-29 19:13 UTC, henriquefonseca requested changes

2021-06-29 19:13 UTC, henriquefonseca commented on util/string_test.go
> +type Foo struct {
Embora eu tenha achado o nome engraçado ele não diz muita coisa. Procurei no restante do código e não achei onde foi usado. Será que era algum teste?

2021-06-30 13:56 UTC, leojasmim commented on api/middlewares.go
> +	boleto.Title.ExpireDateTime = d
@henriquefonseca Boa !!! 👌

2021-06-30 13:57 UTC, leojasmim commented on util/string_test.go
> +type Foo struct {
Acabei esquecendo desse cara no código 😬

2021-06-30 14:13 UTC, henriquefonseca approved these changes

2021-07-01 18:03 UTC, merged