[BPROC-68] Remove fluxo do redis
mundipagg/boleto-api pull request #247
Opened 2021-08-04 14:46 UTC by leojasmim

# Descrição

### Tarefa [BPROC-68](https://mundipagg.atlassian.net/browse/BPROC-68) 

Esta implementação tem por objetivo remover a resiliência/cache realizada no _Redis_ devido aos problemas que vêm ocorrido com o serviço além do fato de não ser a tecnologia recomendada para realização do cache do html do boleto. Continuaremos a ter **resiliência de persistência do Boleto** através do RabbitMQ. Posteriormente faremos um estudo de utilização do AzureBlob para criar um cache de visualização do HTML e do PDF.

Em caso de falha generalizada (MongoDB e RabbitMQ) continuaremos a enviar a URL do Boleto para o cliente e teremos um log que conterá o _payload_ completo do boleto. Esse _payload_ poderá ser manualmente inserido no MongoDB de forma que o cliente volte a acessar o boleto gerado.

![image](https://user-images.githubusercontent.com/18493760/128200048-0453193d-1e50-42d2-a013-bcbb4869619b.png)

### Tipos de alterações

- [ ] Correção de bug 
- [ ] Nova feature 
- [x] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes

Além dos testes da aplicação e do Postman, realizamos um teste simulando uma falha generalizada e a posterior recuperação manual do boleto.

![image](https://user-images.githubusercontent.com/18493760/128200775-33f339dc-e22f-4f81-872b-9c6ce6bae51b.png)

### Teste Local

Quando realizamos a requisição simulando o MongoDB e o RabbitMQ fora do ar conseguimos registrar o boleto com sucesso:

![image](https://user-images.githubusercontent.com/18493760/128201003-b47c25d2-3a8f-4817-8ea2-743446e6271d.png)

Podemos verificar no a falha com o fluxo de resiliência:

![image](https://user-images.githubusercontent.com/18493760/128201199-804f91a4-52c8-48ed-b04e-44ae8556d213.png)

Apesar de registrado com sucesso, não é possível acessar o boleto enquanto o MongoDB estiver fora do ar:

![image](https://user-images.githubusercontent.com/18493760/128201374-c7be3c5b-5eb7-4df9-b5c8-30c2ebaadcb1.png)

![image](https://user-images.githubusercontent.com/18493760/128201401-0a9b83d6-b29d-49e1-a0cb-e19c3addba33.png)

A partir do _payload_ do log, fizemos a inserção manual do boleto no MongoDB. Ressaltamos que é necessário alterar a propriedade `"ID":"610a9fc04dc2e93b1364d6db"` para `"_id":ObjectId("610a9fc04dc2e93b1364d6db")` de forma que a persistência ocorra conforme esperado:

![image](https://user-images.githubusercontent.com/18493760/128201511-4a8b1aca-8825-4717-8f94-3e84dd0c0fbe.png)

Após a inserção manual foi possível recuperar o boleto normalmente:

![image](https://user-images.githubusercontent.com/18493760/128201910-c4bd1b9b-24cb-4416-8773-98304ab3d383.png)

![image](https://user-images.githubusercontent.com/18493760/128201942-7bdb7dfa-c6f6-441f-9579-66f48c65c19c.png)

![image](https://user-images.githubusercontent.com/18493760/128201955-6023b1f0-1ee9-44d4-9f27-13d34a69c252.png)

### Teste Staging

🚧 Em Andamento

## Checklist

- [ ] Associei corretamente a Tarefa do Board ao Pull Request.
- [ ] Meu código segue as diretrizes desse projeto.
- [ ] Eu revisei meu próprio código.
- [ ] Eu comentei meu código em áreas particulares de difícil compreensão.
- [ ] Eu atualizei a documentação de acordo com as mudanças realizadas.
- [ ] Meu código não gerou novos warnings.
- [ ] Eu adicionei testes que provam que minha correção é efetiva ou que a nova feature funciona.
- [ ] Testes novos e existentes passam localmente com minhas alterações. 
- [ ] Testes novos e existentes passam em staging com minhas alterações. 
- [ ] Qualquer dependência dessa alteração já foi realizada (deploy, configuração em todos os ambientes, etc).

2021-08-04 17:24 UTC, henriquefonseca commented on api/boleto.go
> +func getResponseStatusCode(response models.BoletoResponse) int {
Acho que dá para diminuir a quantidade de "ifs" aninhados. Que tal?
```
if len(response.Errors) == 0 {
    return http.StatusOK
}

if response.StatusCode < 1 {
    return http.StatusBadRequest
}

return response.StatusCode
```

2021-08-12 16:07 UTC, tiagor87 commented on api/boleto.go
> +		return
Como você tá dando return em ambos os ifs, não precisa desse else @leojasmim . Assim reduz a complexidade do código.

2021-08-30 18:20 UTC, brunoglm commented on api/boleto.go
> +				err := uploadPayloadBlob(
Realizado o ajuste 😀

2021-08-30 18:21 UTC, brunoglm commented on config/config.go
> +		AzureStorageUploadPath:      os.Getenv("AZURE_STORAGE_UPLOAD_PATH"),
Realizado o ajuste 😀

2021-08-30 18:22 UTC, brunoglm commented on env/install.go
> +	os.Setenv("AZURE_STORAGE_UPLOAD_PATH", "docker/BoletoOnline/Pending")
Realizado o ajuste 😀

2021-08-30 18:22 UTC, brunoglm commented on queue/queueOperation.go
> +			l.Operation = op
Opa, por nada! 😀

2021-08-30 18:22 UTC, brunoglm commented on storage/azure_blob.go
> +			BlockSize:   4 * 1024 * 1024,
Realizado o ajuste 😀

2021-08-30 18:22 UTC, brunoglm commented on storage/azure_blob_test.go
> +	mock.StartMockService("9093")
Realizado o ajuste 😀

2021-08-30 20:39 UTC, vpecanha requested changes

2021-08-30 20:39 UTC, vpecanha commented on api/boleto.go
> +}
Esta função deveria ser de responsabilidade de uma classe que orquestra a criação de um boleto ou de uma classe responsável por expor serviços de blob?

2021-08-30 20:39 UTC, vpecanha commented on api/boleto.go
> +		return http.StatusBadRequest
Porque o default passou a ser BadRequest?

2021-08-30 20:39 UTC, vpecanha commented on api/boleto.go
> +}
Você acha que as configurações de um serviço de blob deveriam ser de responsabilidade de uma classe que gerencia a criação de um boleto ou de uma classe de infraestrutura de blob ?

2021-08-30 20:39 UTC, vpecanha commented on storage/azure_blob.go
> +	Parallelism: 8, //Número de cores da máquina
Porque não criar uma constante igual realizado acima invés do comentário?

2021-08-30 20:39 UTC, vpecanha commented on storage/azure_blob.go
> +	if err = ab.connect(); err != nil {
Porque não logar o erro?

2021-08-30 20:39 UTC, vpecanha commented on storage/azure_blob.go
> +	_, err = azblob.UploadBufferToBlockBlob(ctx, data, blobURL, jsonUploadOptions)
Está ignorando erro, correto? 
Não quebrará as linhas 120 e 121 em caso de erro?

2021-08-30 20:40 UTC, vpecanha requested changes
Senti falta das evidências do teste de carga.

2021-08-30 22:04 UTC, leojasmim commented on storage/azure_blob.go
> +	Parallelism: 8, //Número de cores da máquina
@vpecanha O comentário eu deixei pro @brunoglm ... não era pra ficar não... 😬

2021-08-30 22:12 UTC, leojasmim commented on storage/azure_blob.go
> +	_, err = azblob.UploadBufferToBlockBlob(ctx, data, blobURL, jsonUploadOptions)
@vpecanha Na realidade já está sendo realizada a atribuição a variável de retorno... @brunoglm Mas o Vitor  tem razão... mesmo que não quebre se der um erro vc teria o log de sucesso aqui dentro e o log de erro no pacote `api/boleto` ... Talvez vc possa trazer o log de erro pra dentro dado que lá vc só olha o erro para logar...

2021-08-30 23:19 UTC, leojasmim commented on api/boleto.go
> +		return http.StatusBadRequest
@vpecanha  Já era assim só mudou de lugar
```Go
                if resp.StatusCode > 0 {
			st = resp.StatusCode
		} else {
			st = http.StatusBadRequest
		}
```

2021-08-31 14:28 UTC, leojasmim commented on storage/azure_blob.go
> +	props["Filename"] = filename
@brunoglm Minha ideia aqui era esse cara ser uma propriedade ID mesmo só com o bsonID, sem o `.json` para que seja fácil de vincular com outros logs como por exemplo:

![image](https://user-images.githubusercontent.com/18493760/131520909-f8a191a0-e50c-4164-a631-4c671ba89cbb.png)

2021-08-31 21:02 UTC, brunoglm commented on api/boleto.go
> +}
Realizado o ajuste 😀

2021-08-31 21:03 UTC, brunoglm commented on api/boleto.go
> +}
Realizado o ajuste 😀

2021-08-31 21:03 UTC, brunoglm commented on storage/azure_blob.go
> +	Parallelism: 8, //Número de cores da máquina
Realizado o ajuste 😀

2021-08-31 21:03 UTC, brunoglm commented on storage/azure_blob.go
> +	if err = ab.connect(); err != nil {
Realizado o ajuste 😀

2021-08-31 21:03 UTC, brunoglm commented on storage/azure_blob.go
> +	_, err = azblob.UploadBufferToBlockBlob(ctx, data, blobURL, jsonUploadOptions)
Realizado o ajuste 😀

2021-08-31 21:03 UTC, brunoglm commented on storage/azure_blob.go
> +	props["Filename"] = filename
Realizado o ajuste 😀

2021-09-01 12:25 UTC, vpecanha commented on log/log.go
> +func (l *Log) FallbackErrorWithBasic(msg, msgType string, err error, content interface{}) {
```suggestion
func (l *Log) ErrorWithContent(msg, msgType string, err error, content interface{}) {
```

2021-09-01 17:04 UTC, vpecanha commented on api/boleto.go
>  			if !queue.WriteMessage(p) {
Acho que vale um log de erro dentro do WriteMessage explicitando que não foi possível publiacar na fila

2021-09-01 17:05 UTC, vpecanha commented on api/fallback.go
> +		lg.FallbackErrorWithBasic(persistenceErrorMessage, "Error", err, payload)
Acho que vale diferenciar a mensagem aqui também.. caso falhe a gente não saberá se o problema foi em estabelecer a conexão ou no upload

2021-09-01 18:24 UTC, brunoglm commented on api/boleto.go
>  			if !queue.WriteMessage(p) {
Hoje já existe log para os casos que a aplicação não consegue publicar na fila 😀 

![image](https://user-images.githubusercontent.com/36340027/131723797-34680f6f-428d-4f5a-bd42-42a8068c3077.png)

2021-09-01 18:28 UTC, brunoglm commented on api/fallback.go
> +		lg.FallbackErrorWithBasic(persistenceErrorMessage, "Error", err, payload)
realizado o ajuste 😀

2021-09-01 18:28 UTC, brunoglm commented on log/log.go
> +func (l *Log) FallbackErrorWithBasic(msg, msgType string, err error, content interface{}) {
realizado o ajuste 😀

2021-09-01 19:44 UTC, vpecanha commented on infrastructure/storage/storage.go
> +// GetClient factory storage
Vai funcionar porém isso daqui não é uma factory.

2021-09-01 19:45 UTC, vpecanha approved these changes

2021-09-01 21:19 UTC, leojasmim commented on infrastructure/storage/storage.go
> +// GetClient factory storage
@vpecanha Quando tivermos outros objetos concretos a gente faz a factory da um gás 😬 ❤️

2021-09-01 21:24 UTC, brunoglm approved these changes

2021-09-02 12:09 UTC, merged