[BPROC-209] - Falso positivo registro online de boletos Itau
mundipagg/boleto-api pull request #261
Opened 2021-09-29 14:08 UTC by davidsmedeiros

# Descrição

### Tarefa [CA-427](https://mundipagg.atlassian.net/secure/RapidBoard.jspa?rapidView=76&projectKey=CA&modal=detail&selectedIssue=CA-427) 

Por favor, inclua um resumo da alteração e qual problema foi corrigido ou feature foi adicionada. Inclua também motivação relevante e contexto. Liste todas as dependências necessárias para essa mudança.

### Tipos de alterações

- [ ] Correção de bug 
- [ ] Nova feature 
- [ ] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes

Por favor, descreva os testes que você executou para verificar suas alterações. Forneça instruções necessárias para que seja possível reproduzir os testes e evidências de suas execuções com sucesso.
Se possível, anexe na tarefa a coleção de requisições executadas no teste. (Nesse caso adicione o link abaixo)

### Coleção de Testes [Download](https://www.getpostman.com/collections/83ff1739e979805b1ff6)

### Teste A

Descreva cenário do teste realizado com instruções necessárias para reprodução e evidência de sua execução com sucesso.
Utilize código e/ou imagens (prints) para ilustrar seus teste.

```
{
  "Description": "JSON utilizado no Request do Teste A"
}
```

### Teste B

Descreva cenário do teste realizado com instruções necessárias para reprodução e evidência de sua execução com sucesso.
Utilize código e/ou imagens (prints) para ilustrar seus teste.

```
{
  "Description": "JSON utilizado no Request do Teste B"
}
```

## Checklist

- [ ] Associei corretamente a Tarefa do Board ao Pull Request.
- [ ] Meu código segue as diretrizes desse projeto.
- [ ] Eu revisei meu próprio código.
- [ ] Eu comentei meu código em áreas particulares de difícil compreensão.
- [ ] Eu atualizei a documentação de acordo com as mudanças realizadas.
- [ ] Meu código não gerou novos warnings.
- [ ] Eu adicionei testes que provam que minha correção é efetiva ou que a nova feature funciona.
- [ ] Testes novos e existentes passam localmente com minhas alterações. 
- [ ] Testes novos e existentes passam em staging com minhas alterações. 
- [ ] Qualquer dependência dessa alteração já foi realizada (deploy, configuração em todos os ambientes, etc).

2021-09-29 15:04 UTC, leojasmim requested changes

2021-09-29 15:04 UTC, leojasmim commented on mock/itau.go
> +		c.Data(300, "text/json", []byte("500"))
@davidsmedeiros Acabou que no mock vc simulou com HttpStatusCode 500 e 300 ... Entendi que ele fará pra qualquer StatusCode dado esse body porém acho que pode trocar o 300 pelo 200 aqui no mock.

2021-09-29 15:16 UTC, davidsmedeiros commented on mock/itau.go
> +		c.Data(300, "text/json", []byte("500"))
Você diz no Status code do erro do bug? Se inserir 501 content do body desse mock vai querar porque é verificado somente quando recebemos 500 no content.

2021-09-29 16:36 UTC, leojasmim commented
@davidsmedeiros Da um check no linter tbm

2021-09-29 17:05 UTC, wesleycosta commented on env/install.go
> +	os.Setenv("AZURE_STORAGE_ACCOUNT", "devstoreaccount1")
dúvida esse chave é do azure local que sobe no docker-compose?
se não for, acredito que não seria bom a gente comitar esse carinha já que é um repo público...

2021-09-29 17:11 UTC, leojasmim commented on mock/itau.go
> +		c.Data(300, "text/json", []byte("500"))
Isso

2021-09-29 17:12 UTC, leojasmim commented on env/install.go
> +	os.Setenv("AZURE_STORAGE_ACCOUNT", "devstoreaccount1")
@wesleycosta Esse é default do emulador do Azure, então acredito que possa ficar fixo tal qual as urls dos serviços locais

2021-09-29 18:50 UTC, leojasmim approved these changes

2021-09-29 19:32 UTC, VictorSamp submitted a review, later dismissed

2021-10-01 16:04 UTC, brunoglm submitted a review, later dismissed

2021-10-01 16:36 UTC, wesleycosta approved these changes

2021-10-01 17:19 UTC, leojasmim submitted a review, later dismissed

2021-10-01 17:20 UTC, wesleycosta submitted a review, later dismissed

2021-10-01 18:37 UTC, VictorSamp submitted a review, later dismissed

2021-10-04 12:57 UTC, vpecanha commented on itau/itau.go
> +	if bodyContent == "500" {
Nesse caso eles não retornam código de barras e linha digitável no response, pelo que vi na evidências do PR.

Porque não verificamos esses campos invés de deixar estático 500? Digo isso pois se eles começarem a retornar 503 vamos voltar com o problema.

2021-10-04 16:32 UTC, vpecanha commented on itau/itau.go
> +	validBoletoData := boletoResponse.BarCodeNumber != "" && boletoResponse.DigitableLine != ""
Tem uma classe que tem um regex que verifica a string. Acho que ela é utilizada no citibank e da pra utilizar aqui também

2021-10-04 18:08 UTC, leojasmim approved these changes

2021-10-04 18:23 UTC, leojasmim approved these changes

2021-10-04 20:06 UTC, davidsmedeiros commented on itau/itau.go
> +	validBoletoData := boletoResponse.BarCodeNumber != "" && boletoResponse.DigitableLine != ""
feito

2021-10-04 20:26 UTC, davidsmedeiros commented on itau/itau.go
> +	if bodyContent == "500" {
done

2021-10-04 20:30 UTC, wesleycosta approved these changes

2021-10-04 20:41 UTC, brunoglm approved these changes

2021-10-04 20:49 UTC, vpecanha reviewed
Passará dado que é um bug e o cliente está prejudicado porém não deveríamos subir pois tem dois métodos novos que literalmente fazem a mesma coisa.

Deveria estar dentro do string utils existente evitando duplicação

2021-10-05 12:56 UTC, merged