[BPROC-232] - Registro de boleto JPMorgan na boleto-api
mundipagg/boleto-api pull request #264
Opened 2021-10-20 17:49 UTC by davidsmedeiros

# Descrição

### Tarefa [BPROC-232](https://mundipagg.atlassian.net/browse/BPROC-232) 

Este PR diz respeito ao registro de boleto da JPMorgan. Foi realizado a integração da JPMorgan na boleto-api. Para isso, foi preciso criar as variáveis de ambiente dentro da boleto-api referentes ao banco, adição do fluxo de validações e tratamento de erros, mapeamento do request da boleto-api para o request da JPMorgan. Foi feito também as requisições a partir de dados fake para utilização em ambiente de desenvolvimento sem a necessidade de utilizar os certificados localmente.

### Tipos de alterações

- [ ] Correção de bug 
- [x] Nova feature 
- [ ] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes

Foram realizados a bateria de testes unitários. Os resultados são mostrados na imagem abaixo.

![image](https://user-images.githubusercontent.com/88195864/138151318-36103f8f-16a6-48f4-a581-9ffa46f88e00.png)

As requisições de testes para a JPMorgan foram adicionados na coleção do postman junto com os demais bancos.
A coleção de testes foi realizado localmente. Os resultados são mostrados na imagem abaixo.

![image](https://user-images.githubusercontent.com/88195864/138294127-c8f8cfda-dfc2-4c90-896e-dfdcf5509267.png)

A figura abaixo mostra uma requisição de sucesso para a boleto api via postman e na imagem seguinte a resposta mapeada da JPMorgan para a boleto-api.

![image](https://user-images.githubusercontent.com/88195864/138298244-a68ceb5c-e21f-4305-9291-02e5b98e1221.png)

![image](https://user-images.githubusercontent.com/88195864/138298314-3f0154e1-78fd-4abc-a9d1-6b16459a4f6e.png)

A imagem abaixo mostra uma requisição com erro e a imagem seguinte a resposta dessa requisição.

![image](https://user-images.githubusercontent.com/88195864/138298641-9a6fbf1c-8fe0-4689-9be1-51b634aed469.png)

![image](https://user-images.githubusercontent.com/88195864/138299687-8a93da3a-1601-4e08-ab00-f75a270e6148.png)

Para erros relacionados aos certificados. A resposta para qualquer requisição será conforme as imagens abaixo.

Para erro com o certificado de assinatura

![image](https://user-images.githubusercontent.com/88195864/138300733-6ba55c14-3458-42a2-9cdd-5887a53ba136.png)

Para erro com o certificado de transporte 

![image](https://user-images.githubusercontent.com/88195864/138300820-49c987ce-9cd3-41d9-ade5-6ab2e5987457.png)

Foi criado uma coleção no Postman que realiza as requisições com erros mapeados. A imagem abaixo mostra o resultado desse teste.

![image](https://user-images.githubusercontent.com/88195864/138705706-ff973991-c6c7-470c-893c-f137b0066198.png)

## Checklist

- [ ] Associei corretamente a Tarefa do Board ao Pull Request.
- [ ] Meu código segue as diretrizes desse projeto.
- [ ] Eu revisei meu próprio código.
- [ ] Eu comentei meu código em áreas particulares de difícil compreensão.
- [ ] Eu atualizei a documentação de acordo com as mudanças realizadas.
- [ ] Meu código não gerou novos warnings.
- [ ] Eu adicionei testes que provam que minha correção é efetiva ou que a nova feature funciona.
- [ ] Testes novos e existentes passam localmente com minhas alterações. 
- [ ] Testes novos e existentes passam em staging com minhas alterações. 
- [ ] Qualquer dependência dessa alteração já foi realizada (deploy, configuração em todos os ambientes, etc).

2021-10-29 20:57 UTC, leojasmim commented on api/errors_test.go
> +// func Test_GetMapper_WhenBankStone_ReturnStoneErrorsCode(t *testing.T) {
@davidsmedeiros Pode remover esses testes dado que a função foi removida

2021-10-29 21:35 UTC, leojasmim requested changes

2021-10-29 21:35 UTC, leojasmim commented on bank/services/jpmorgan/contracts.go
> +// DataError objeto de erro
@davidsmedeiros O summary não é necessário dado que a estrutura é privada

2021-10-29 21:35 UTC, leojasmim commented on bank/services/jpmorgan/contracts.go
> +        "txtInfCliCed": "{{.Recipient.Name}}"
@davidsmedeiros Acredito que seria importante esse cara utilizar o _truncateOnly_

2021-10-29 21:35 UTC, leojasmim commented on bank/services/jpmorgan/jpmorgan.go
> +	errorResponse := models.GetBoletoResponseError("MP500", "Internal Error")
@davidsmedeiros Poderíamos colocar uma mensagem mais significativa sobre o erro aqui, ao invés do `Internal Error`, de forma a melhor identificar o problema ... foi mal não ter dado essa sugestão inicialmente 😢 
```suggestion
}

func (b bankJPMorgan) encryptedBody(body string) (string, *models.BoletoResponse) {
	sk, err := certificate.GetCertificateFromStore(config.Get().AzureStorageJPMorganSignCrtName)
	if err != nil {
		responseError := models.GetBoletoResponseError("MP500", "fail on load digital signature certificate")
		return "", &responseError
	}
	bodyEncripted, err := b.jwtSigner.Sign(body, sk.([]byte))
	if err != nil {
		responseError := models.GetBoletoResponseError("MP500", "fail on encrypt request body")
		return "", &responseError
	}
	return bodyEncripted, nil
}
```

2021-10-29 21:35 UTC, leojasmim commented on bank/services/jpmorgan/jpmorgan.go
> +	var bodyEncripted string
@davidsmedeiros Declaração desnecessária

2021-10-29 21:35 UTC, leojasmim commented on bank/services/jpmorgan/jpmorgan.go
> +	bodyEncripted, BoletoResponseError := b.encriptedBody(body)
@davidsmedeiros 
```suggestion
		bodyEncripted, encryptedErr := b.encryptedBody(body)
	if encryptedErr != nil {
		return *encryptedErr, nil
	}
```

2021-10-29 21:35 UTC, leojasmim commented on bank/services/jpmorgan/jpmorgan.go
> +		if "application/xml" == contentType {
@davidsmedeiros Aqui ficou um _Yoda condition_
```suggestion
		if contentType == "application/xml"{
```

2021-10-29 21:35 UTC, leojasmim commented on bank/services/jpmorgan/jpmorgan.go
> +		} else if "application/json" == contentType {
@davidsmedeiros Aqui ficou um _Yoda condition_
```suggestion
		if contentType == "application/xml"{
```

2021-10-29 21:35 UTC, leojasmim commented on bb/bb.go
> +	var erros = make(map[string]int)
@davidsmedeiros Aqui o retorno deveria ser `nil`

2021-10-29 21:39 UTC, leojasmim requested changes

2021-10-29 21:39 UTC, leojasmim commented on bank/services/jpmorgan/stub.go
> +		s.Title.BoletoType = bt
@davidsmedeiros aqui não há neessidade do switch dado que apenas a DM é aceitas na JP no momento.
```suggestion
		s.Title.BoletoType, s.Title.BoletoTypeCode = "DM", "02"
		return s
```

2021-11-03 22:59 UTC, leojasmim approved these changes

2021-11-04 11:35 UTC, wesleycosta submitted a review, later dismissed

2021-11-04 12:20 UTC, VictorSamp submitted a review, later dismissed

2021-11-04 12:39 UTC, wesleycosta approved these changes

2021-11-04 12:39 UTC, brunoglm approved these changes

2021-11-04 12:39 UTC, VictorSamp approved these changes

2021-11-04 12:40 UTC, leojasmim approved these changes

2021-11-04 12:44 UTC, merged