:mute: mascara authorization header
mundipagg/boleto-api pull request #272
Opened 2021-11-16 20:09 UTC by leojasmim

# Descrição

### Tarefa [BPROC-285](https://mundipagg.atlassian.net/browse/BPROC-285) 

O objetivo desta tarefa é mascarar o nó de **Authorization** que atualmente é enviado no header da requisição com as credenciais do usuário da aplicação.

### Tipos de alterações

- [x] Correção de bug 
- [ ] Nova feature 
- [ ] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes

### Teste Local

Após a correção passamos a logar o campo devidamente mascarado:

![image](https://user-images.githubusercontent.com/18493760/142058225-313d3cff-3180-4507-9852-d9a2d93c2b3b.png)

### Teste Staging

🚧 Em andamento

## Checklist

- [ ] Associei corretamente a Tarefa do Board ao Pull Request.
- [ ] Meu código segue as diretrizes desse projeto.
- [ ] Eu revisei meu próprio código.
- [ ] Eu comentei meu código em áreas particulares de difícil compreensão.
- [ ] Eu atualizei a documentação de acordo com as mudanças realizadas.
- [ ] Meu código não gerou novos warnings.
- [ ] Eu adicionei testes que provam que minha correção é efetiva ou que a nova feature funciona.
- [ ] Testes novos e existentes passam localmente com minhas alterações. 
- [ ] Testes novos e existentes passam em staging com minhas alterações. 
- [ ] Qualquer dependência dessa alteração já foi realizada (deploy, configuração em todos os ambientes, etc).

2021-11-17 02:38 UTC, brunoglm commented on util/http.go
>  func HeaderToMap(h http.Header) map[string]string {
```suggestion
.......
func HeaderToMap(h http.Header) map[string]string {
	m := make(map[string]string)
	for k, v := range h {
            m[k] = v[0]
	}
	
	if _ , hasKey := m["Authorization"]; hasKey {
            m["Authorization"] = "***"
        }
	
	return m
}
.......
```

2021-11-17 02:41 UTC, brunoglm commented on util/http.go
>  func HeaderToMap(h http.Header) map[string]string {
@leojasmim, coloquei uma sugestão na tratativa, que talvez diminua a complexidade do código, e não fazemos o processamento do IF em todo o for. Vê se faz sentido

2021-11-17 10:36 UTC, leojasmim commented on util/http.go
>  func HeaderToMap(h http.Header) map[string]string {
@brunoglm Apesar de parecer melhor,  a complexidade da comparação é constante  O(1). Logo se considerarmos a complexidade do loop O(N) logo a complexidade geral da primeira implementação seria O(N). Na segunda implementação realizamos o loop e após uma busca, que tem complexidade teórica de O(log n). Assim a complexidade geral seria ligeiramente maior, i.e., O(N log n). Realizamos a implementação da segunda versão e criamos um benchmark para verificar o desempenho:

![image](https://user-images.githubusercontent.com/18493760/142184239-35b8c5c5-fa65-4aca-828f-85b39374c6e2.png)

![image](https://user-images.githubusercontent.com/18493760/142184261-974f880d-4c32-45ad-9ca0-b1cc8b15a22c.png)

Verificamos que a função que realiza a busca é ligeiramente menos performática. Em linhas gerais, esse método será utilizado com maps pequenos, logo não deve haver grande impacto geral, porém em maps maiores poderia impactar a performance 👍 .

2021-11-17 13:02 UTC, brunoglm commented on util/http.go
>  func HeaderToMap(h http.Header) map[string]string {
boaa @brunoglm, top 😀

2021-11-17 13:04 UTC, brunoglm submitted a review, later dismissed

2021-11-17 19:01 UTC, VictorSamp approved these changes

2021-11-17 19:12 UTC, davidsmedeiros approved these changes

2021-11-17 20:19 UTC, vpecanha approved these changes

2021-11-17 22:03 UTC, cersouza commented on util/http_test.go
> +	h := make(http.Header)
Mano, apesar de ser implícito, será que não faria sentido renomear a variável `h` por `header` para melhorar a legibilidade?

2021-11-17 22:19 UTC, cersouza requested changes

2021-11-17 22:19 UTC, cersouza commented on util/http.go
> +		}
Mano, eu sugeriria renomear as variáveis `h`, `m`, `k` e `v` para nomes mais descritivos de acordo com o contexto para melhorar a legibilidade . O que acha?

2021-11-17 22:24 UTC, davidsmedeiros approved these changes

2021-11-19 18:42 UTC, brunoglm approved these changes

2021-11-30 12:39 UTC, merged