[QA-1429] Converter a pipeline para YML
mundipagg/boleto-api pull request #275
Opened 2021-12-01 02:09 UTC by vannessasoares

# Descrição

### Tarefa [CA-427](https://mundipagg.atlassian.net/secure/RapidBoard.jspa?rapidView=76&projectKey=CA&modal=detail&selectedIssue=CA-427) 

Por favor, inclua um resumo da alteração e qual problema foi corrigido ou feature foi adicionada. Inclua também motivação relevante e contexto. Liste todas as dependências necessárias para essa mudança.

### Tipos de alterações

- [ ] Correção de bug 
- [ ] Nova feature 
- [ ] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes

Por favor, descreva os testes que você executou para verificar suas alterações. Forneça instruções necessárias para que seja possível reproduzir os testes e evidências de suas execuções com sucesso.
Se possível, anexe na tarefa a coleção de requisições executadas no teste. (Nesse caso adicione o link abaixo)

### Coleção de Testes [Download](https://www.getpostman.com/collections/83ff1739e979805b1ff6)

### Teste A

Descreva cenário do teste realizado com instruções necessárias para reprodução e evidência de sua execução com sucesso.
Utilize código e/ou imagens (prints) para ilustrar seus teste.

```
{
  "Description": "JSON utilizado no Request do Teste A"
}
```

### Teste B

Descreva cenário do teste realizado com instruções necessárias para reprodução e evidência de sua execução com sucesso.
Utilize código e/ou imagens (prints) para ilustrar seus teste.

```
{
  "Description": "JSON utilizado no Request do Teste B"
}
```

## Checklist

- [ ] Associei corretamente a Tarefa do Board ao Pull Request.
- [ ] Meu código segue as diretrizes desse projeto.
- [ ] Eu revisei meu próprio código.
- [ ] Eu comentei meu código em áreas particulares de difícil compreensão.
- [ ] Eu atualizei a documentação de acordo com as mudanças realizadas.
- [ ] Meu código não gerou novos warnings.
- [ ] Eu adicionei testes que provam que minha correção é efetiva ou que a nova feature funciona.
- [ ] Testes novos e existentes passam localmente com minhas alterações. 
- [ ] Testes novos e existentes passam em staging com minhas alterações. 
- [ ] Qualquer dependência dessa alteração já foi realizada (deploy, configuração em todos os ambientes, etc).

2021-12-02 11:47 UTC, williangl submitted a review, later dismissed

2021-12-02 12:41 UTC, ramsessacol approved these changes
![nice](https://user-images.githubusercontent.com/89397089/144423834-92695384-76f4-4c02-bcc2-42baa45c95f1.jpeg)

2021-12-02 13:10 UTC, PauloGoncalvesBH requested changes

2021-12-02 13:10 UTC, PauloGoncalvesBH commented on devops/azure-pipeline.yml
> +                docker-compose run --rm -e PACT_BROKER_TOKEN=$(PACT_BROKER_TOKEN) -e PACT_URL=$(PACT_URL) -e GITHUB_COMMIT=$(Build.SourceVersion) -e GITHUB_BRANCH=$(Build.SourceBranchName) -e PACT_BR
O que acha de quebrar o comando em várias linhas para facilitar a leitura?
```suggestion
                docker-compose run --rm \
                -e PACT_BROKER_TOKEN=$(PACT_BROKER_TOKEN) \
                -e PACT_URL=$(PACT_URL) \
                -e GITHUB_COMMIT=$(Build.SourceVersion) \
                -e GITHUB_BRANCH=$(Build.SourceBranchName) \
                -e PACT_BROKER_URL=https://pagarme.pactflow.io/ \
                contract-test
```

2021-12-02 13:10 UTC, PauloGoncalvesBH commented on devops/azure-pipeline.yml
> +                docker-compose run --rm -e PACT_BROKER_TOKEN=$(PACT_BROKER_TOKEN) -e PACT_URL=$(PACT_URL) -e GITHUB_COMMIT=$(Build.SourceVersion) -e GITHUB_BRANCH=$(Build.SourceBranchName) -e PACT_BR
Uma dúvida breve não relacionado à pipeline:
O `PACT_BROKER_URL` do teste de contrato ficou como variável de ambiente?

2021-12-02 13:44 UTC, vannessasoares commented on devops/azure-pipeline.yml
> +                docker-compose run --rm -e PACT_BROKER_TOKEN=$(PACT_BROKER_TOKEN) -e PACT_URL=$(PACT_URL) -e GITHUB_COMMIT=$(Build.SourceVersion) -e GITHUB_BRANCH=$(Build.SourceBranchName) -e PACT_BR
@PauloGoncalvesBH ficou sim! aqui https://github.com/mundipagg/boleto-api/blob/db4e7159b1cc86b4919bcd499863861ae2c57186/test/boleto_pact_provider_test.go#L137

2021-12-02 15:28 UTC, brunoglm approved these changes

2021-12-02 15:28 UTC, williangl approved these changes

2021-12-02 16:43 UTC, giselerosa approved these changes

2021-12-27 13:53 UTC, PauloGoncalvesBH approved these changes

2021-12-27 15:10 UTC, ramsessacol approved these changes

2021-12-28 20:09 UTC, merged