[BPROC-389] Adição de campo Sacador Avalista na CEF no request e no layout do boleto
mundipagg/boleto-api pull request #282
Opened 2022-03-03 21:00 UTC by davidsmedeiros

# Descrição

### Tarefa [BPROC-389](https://mundipagg.atlassian.net/browse/BPROC-389) 

Este PR adiciona o campo SACADOR_AVALISTA no request para a Caixa. Além disso, Adiciona essas informações no layout do boleto gerado.

### Tipos de alterações

- [] Correção de bug 
- [x] Nova feature 
- [ ] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes

Foram criados testes unitários e execução da coleção de testes do postman local.

![image](https://user-images.githubusercontent.com/88195864/152857403-36500f8c-a0ef-420c-bbfc-1528aed7f73b.png)

Evidência do=e envio do campo no request

![image](https://user-images.githubusercontent.com/88195864/155221449-3145c924-e765-4b1f-aec8-4b870ad45a60.png)

Evidência da adição dos campos no layout do boleto

![image](https://user-images.githubusercontent.com/88195864/155221566-362a42d0-affd-4ed5-8203-bfef616b8cbf.png)

## Checklist

- [ ] Associei corretamente a Tarefa do Board ao Pull Request.
- [x] Meu código segue as diretrizes desse projeto.
- [x] Eu revisei meu próprio código.
- [ ] Eu comentei meu código em áreas particulares de difícil compreensão.
- [ ] Eu atualizei a documentação de acordo com as mudanças realizadas.
- [ ] Meu código não gerou novos warnings.
- [x] Eu adicionei testes que provam que minha correção é efetiva ou que a nova feature funciona.
- [x] Testes novos e existentes passam localmente com minhas alterações. 
- [ ] Testes novos e existentes passam em staging com minhas alterações. 
- [ ] Qualquer dependência dessa alteração já foi realizada (deploy, configuração em todos os ambientes, etc).

2022-03-04 12:19 UTC, brunoglm submitted a review, later dismissed

2022-03-04 17:08 UTC, leojasmim commented
@davidsmedeiros Acho que não entendi bem a tarefa... do jeito que foi feito estamos passando os dados do Recipient (Beneficiário) tanto no beneficiário quanto no Sacador... Acredito que não seja esse o objetivo pois esses dados são distintos, logo deveríamos incluir no contrato do BoletoRequest um campo para receder os dados do sacador (Nome e Documento)

2022-03-09 15:21 UTC, brunoglm commented on caixa/caixa_test.go
> +	assert.Contains(t, no_content, "<RAZAO_SOCIAL>Recipient Test Name</RAZAO_SOCIAL>", "Erro no mapeamento do campo Recipient")
Aqui, seria bacana ter um assert sobre o nó `<CNPJ>` , o que acha ? 😀

2022-03-09 15:23 UTC, brunoglm commented on caixa/caixa_test.go
> +	assert.Contains(t, node_content, "<NOME>Recipient Test Name</NOME>", "Erro no mapeamento do campo Recipient")
Aqui seria bacana ter um assert sobre o nó `<CPF>` , o que acha ? 😀

2022-03-09 15:26 UTC, brunoglm commented on caixa/caixa_test.go
> +	node_content := test.GetNode(b, "SACADOR_AVALISTA")
Aqui acho que ficaria melhor com o padrão de variáveis Golang 😀

```suggestion
	nodeContent := test.GetNode(b, "SACADOR_AVALISTA")
```

2022-03-09 15:28 UTC, brunoglm commented on caixa/caixa_test.go
> +	assert.NotContains(t, node_content, "<NOME>Recipient Test Name</NOME>", "Erro no mapeamento do campo Recipient")
Aqui seria bacana ter um assert sobre o nó <CPF> , o que acha ? 😀

2022-03-09 15:29 UTC, brunoglm commented on caixa/caixa_test.go
> +	assert.NotContains(t, node_content, "<RAZAO_SOCIAL>Recipient Test Name</RAZAO_SOCIAL>", "Erro no mapeamento do campo Recipient")
Aqui seria bacana ter um assert sobre o nó `<CNPJ>` , o que acha ? 😀

2022-03-09 15:33 UTC, brunoglm commented on test/stub.go
> +func (s *StubBoletoRequest) WithRecipientDocumentType(DocumentType string) *StubBoletoRequest {
Opa, o padrão de parâmetro da função é Camel case 😀  
```suggestion
func (s *StubBoletoRequest) WithRecipientDocumentType(documentType string) *StubBoletoRequest {
```

2022-03-09 15:33 UTC, brunoglm commented on test/stub.go
> +	s.Recipient.Document.Type = DocumentType
Opa, o padrão de parâmetro da função é Camel case 😀  
```suggestion
	s.Recipient.Document.Type = documentType
```

2022-03-09 15:34 UTC, brunoglm commented on test/stub.go
> +	s.Recipient.Name = RecipientName
Opa, o padrão de parâmetro da função é Camel case 😀  
```suggestion
	s.Recipient.Name = recipientName
```

2022-03-09 15:37 UTC, brunoglm commented on test/test.go
> +type Node struct {
Obrigado por isso @davidsmedeiros 💯  . Sugestão pra ficar mais claro o objetivo 😀 
```suggestion
type XmlNode struct {
```

2022-03-09 15:39 UTC, brunoglm commented on test/test.go
> +func Walk(nodes []Node, f func(Node) bool) {
Obrigado por isso @davidsmedeiros 💯 . Sugestão pra ficar mais claro o objetivo 😀
```suggestion
func WalkThroughXml(nodes []Node, f func(Node) bool) {
```

2022-03-09 15:44 UTC, brunoglm commented on boleto/templateCaixa.go
> +                            <td><span class="text"><b>Sacador/Avalista: </b> &nbsp;{{.View.Boleto.Recipient.Name}}</span></td>
opa, aqui não precisa ter um corte na quantidade de caracteres do nome ? Caso o cliente passe um nome muito grande, não quebraria essa <TD> ? 😀

2022-03-09 15:47 UTC, brunoglm reviewed
@davidsmedeiros senti falta de evidência com o type CPF 😀

2022-03-09 15:48 UTC, brunoglm commented on caixa/caixa_test.go
> +	node_content := test.GetNode(b, "SACADOR_AVALISTA")
Aqui acho que ficaria melhor com o padrão de variáveis Golang 😀
```suggestion
	nodeContent := test.GetNode(b, "SACADOR_AVALISTA")
```

2022-03-09 15:48 UTC, brunoglm commented on caixa/caixa_test.go
> +	node_content := test.GetNode(b, "SACADOR_AVALISTA")
Aqui acho que ficaria melhor com o padrão de variáveis Golang 😀
```suggestion
	nodeContent := test.GetNode(b, "SACADOR_AVALISTA")
```

2022-03-09 15:50 UTC, brunoglm commented on caixa/caixa_test.go
> +func TestTemplateRequestCaixa_WhenRequestWithSacadorAvalistaDocumentInNotValidCPF_ParseFailed(t *testing.T) {
Seria bacana esse teste com o cenário inverso, passando o type CNPJ, e passando um doc CPF talvez, o que acha ? 😀

2022-03-09 15:51 UTC, brunoglm commented on caixa/caixa_test.go
> +	doc := "00732159000109"
uma sugestão pra deixar mais claro o nome dessa variável 😀 
```suggestion
	cnpjDocument:= "00732159000109"
```

2022-03-09 19:02 UTC, davidsmedeiros commented on boleto/templateCaixa.go
> +                            <td><span class="text"><b>Sacador/Avalista: </b> &nbsp;{{.View.Boleto.Recipient.Name}}</span></td>
![image](https://user-images.githubusercontent.com/88195864/157512966-169db059-1643-4f81-971b-19794c602041.png)

2022-03-09 20:16 UTC, brunoglm approved these changes
Boaa, mandou bem @davidsmedeiros 🚀 🚀 🚀

2022-03-11 20:07 UTC, brunoglm submitted a review, later dismissed

2022-03-12 12:27 UTC, leojasmim commented on caixa/request.go
> +                              <RAZAO_SOCIAL>{{truncateOnly (.Shopkeeper.Name) 40}}</RAZAO_SOCIAL>
@davidsmedeiros Aqui ficou o nome ao invés do document

2022-03-12 12:28 UTC, leojasmim commented on models/shopkeeper.go
> +type Shopkeeper struct {
@davidsmedeiros Conforme conversamos vamos mudar o nome para **PayeeGuarantor**

2022-03-12 12:30 UTC, leojasmim requested changes
Comentei uns pontos aqui @davidsmedeiros

2022-03-15 19:40 UTC, davidsmedeiros commented on caixa/request.go
> +                              <RAZAO_SOCIAL>{{truncateOnly (.Shopkeeper.Name) 40}}</RAZAO_SOCIAL>
A ordem é assim:
se for cpf
CPF
NOME
caso seja cnpj
CPNJ
RAZAO_SOCIAL

2022-03-15 20:11 UTC, davidsmedeiros commented on caixa/caixa_test.go
> +	assert.Contains(t, nodeContent, fmt.Sprintf("<CPF>%s</CPF>", input.Shopkeeper.Document.Number), "Erro no mapeamento do document type do Shopkeeper")
Não haveria. Essa mensagem que está aí é pra orientar o porque esse teste falhou

2022-03-15 20:11 UTC, davidsmedeiros commented on caixa/caixa_test.go
> +	assert.Contains(t, nodeContent, fmt.Sprintf("<CPF>%s</CPF>", input.Shopkeeper.Document.Number), "Erro no mapeamento do document type do Shopkeeper")
Não haveria. Essa mensagem que está aí é pra orientar o porque esse teste falhou

2022-03-16 13:36 UTC, leojasmim submitted a review, later dismissed

2022-03-16 14:04 UTC, brunoglm approved these changes

2022-03-16 18:25 UTC, cersouza submitted a review, later dismissed

2022-03-17 12:14 UTC, leojasmim approved these changes

2022-03-17 12:37 UTC, brunoglm submitted a review, later dismissed

2022-03-21 11:13 UTC, leojasmim approved these changes

2022-03-21 13:02 UTC, VictorSamp approved these changes

2022-03-22 12:57 UTC, merged