feat: adiciona data maxima de vencimento shopfacil e netempresa
mundipagg/boleto-api pull request #287
Opened 2022-03-24 16:04 UTC by VictorSamp

# Descrição

### Tarefa [CA-427](https://mundipagg.atlassian.net/secure/RapidBoard.jspa?rapidView=76&projectKey=CA&modal=detail&selectedIssue=CA-427) 

Por favor, inclua um resumo da alteração e qual problema foi corrigido ou feature foi adicionada. Inclua também motivação relevante e contexto. Liste todas as dependências necessárias para essa mudança.

### Tipos de alterações

- [ ] Correção de bug 
- [ ] Nova feature 
- [ ] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes

Por favor, descreva os testes que você executou para verificar suas alterações. Forneça instruções necessárias para que seja possível reproduzir os testes e evidências de suas execuções com sucesso.
Se possível, anexe na tarefa a coleção de requisições executadas no teste. (Nesse caso adicione o link abaixo)

### Coleção de Testes [Download](https://www.getpostman.com/collections/83ff1739e979805b1ff6)

### Teste A

Descreva cenário do teste realizado com instruções necessárias para reprodução e evidência de sua execução com sucesso.
Utilize código e/ou imagens (prints) para ilustrar seus teste.

```
{
  "Description": "JSON utilizado no Request do Teste A"
}
```

### Teste B

Descreva cenário do teste realizado com instruções necessárias para reprodução e evidência de sua execução com sucesso.
Utilize código e/ou imagens (prints) para ilustrar seus teste.

```
{
  "Description": "JSON utilizado no Request do Teste B"
}
```

## Checklist

- [ ] Associei corretamente a Tarefa do Board ao Pull Request.
- [ ] Meu código segue as diretrizes desse projeto.
- [ ] Eu revisei meu próprio código.
- [ ] Eu comentei meu código em áreas particulares de difícil compreensão.
- [ ] Eu atualizei a documentação de acordo com as mudanças realizadas.
- [ ] Meu código não gerou novos warnings.
- [ ] Eu adicionei testes que provam que minha correção é efetiva ou que a nova feature funciona.
- [ ] Testes novos e existentes passam localmente com minhas alterações. 
- [ ] Testes novos e existentes passam em staging com minhas alterações. 
- [ ] Qualquer dependência dessa alteração já foi realizada (deploy, configuração em todos os ambientes, etc).

2022-03-24 19:20 UTC, vgpecanha approved these changes
Orgulho do papai: 💯 % de cobertura de código!! 🔥 🥇

2022-03-24 19:20 UTC, vgpecanha commented on bradescoShopFacil/bradescoShopFacil.go
> +	b.validate.Push(bradescoShopFacilMaxExpirationDateValidate)
Não consigo achar isso bonito kkkkk

2022-03-24 19:20 UTC, vgpecanha commented on bradescoShopFacil/stub.go
> +	s.Agreement = models.Agreement{
Fica aí dica de, na próxima, criar builders ou qualquer outro gerador de dados aleatórios. Dessa maneira você tornará o código mais reaproveitável para os próximos devs cujo necessitarão criar um fake/stub de objetos de agreement, authentication e etc

2022-03-25 19:10 UTC, VictorSamp commented on bradescoShopFacil/bradescoShopFacil.go
> +	b.validate.Push(bradescoShopFacilMaxExpirationDateValidate)
alterado

2022-03-28 17:21 UTC, brunoglm submitted a review, later dismissed

2022-03-28 17:38 UTC, cersouza requested changes

2022-03-29 12:11 UTC, leojasmim commented on bradescoNetEmpresa/validations.go
> -func bradescoNetEmpresaValidateAgreement(b interface{}) error {
@VictorSamp Não entendi porque removemos essa validação?

2022-03-29 12:17 UTC, leojasmim reviewed
Deixei um comentário ae 👁️

2022-03-29 13:17 UTC, davidsmedeiros submitted a review, later dismissed

2022-03-29 13:17 UTC, davidsmedeiros commented on bradescoShopFacil/validations.go
> +	maxExpDate, _ := time.Parse("2006-01-02", "2025-02-21")
@VictorSamp uma maneira seria coloca-la em validations/utils.go que aí daria pra aproveitar para todos os bancos. Como essa validação serve para todos, não vejo problema em estar lá. Ela ficaria para cada banco caso fosse algo muito específico, o que não é o caso.

2022-03-29 17:45 UTC, leojasmim submitted a review, later dismissed

2022-03-29 17:55 UTC, cersouza approved these changes
Cara, se o @vgpecanha e o @leojasmim já aprovaram, tenho nem o que falar rsrs.... Mas boa mano! 🐇

2022-03-30 17:42 UTC, brunoglm approved these changes

2022-04-06 14:14 UTC, vgpecanha approved these changes

2022-04-06 20:35 UTC, davidsmedeiros approved these changes

2022-04-12 13:04 UTC, leojasmim approved these changes

2022-04-12 13:04 UTC, merged