[BPROC-429] - Juros e Multa na Stone
mundipagg/boleto-api pull request #290
Opened 2022-04-18 14:55 UTC by davidsmedeiros

# Descrição

### Tarefa [BPROC-429](https://mundipagg.atlassian.net/secure/RapidBoard.jspa?rapidView=76&projectKey=CA&modal=detail&selectedIssue=BPROC-429) 

Adição da feature de juros e multa para o boleto stone.

### Tipos de alterações

- [ ] Correção de bug 
- [x] Nova feature 
- [ ] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes

Por favor, descreva os testes que você executou para verificar suas alterações. Forneça instruções necessárias para que seja possível reproduzir os testes e evidências de suas execuções com sucesso.
Se possível, anexe na tarefa a coleção de requisições executadas no teste. (Nesse caso adicione o link abaixo)

### Coleção de Testes [Download](https://www.getpostman.com/collections/83ff1739e979805b1ff6)

### Teste A

Descreva cenário do teste realizado com instruções necessárias para reprodução e evidência de sua execução com sucesso.
Utilize código e/ou imagens (prints) para ilustrar seus teste.

```
{
  "Description": "JSON utilizado no Request do Teste A"
}
```

### Teste B

Descreva cenário do teste realizado com instruções necessárias para reprodução e evidência de sua execução com sucesso.
Utilize código e/ou imagens (prints) para ilustrar seus teste.

```
{
  "Description": "JSON utilizado no Request do Teste B"
}
```

## Checklist

- [ ] Associei corretamente a Tarefa do Board ao Pull Request.
- [ ] Meu código segue as diretrizes desse projeto.
- [ ] Eu revisei meu próprio código.
- [ ] Eu comentei meu código em áreas particulares de difícil compreensão.
- [ ] Eu atualizei a documentação de acordo com as mudanças realizadas.
- [ ] Meu código não gerou novos warnings.
- [ ] Eu adicionei testes que provam que minha correção é efetiva ou que a nova feature funciona.
- [ ] Testes novos e existentes passam localmente com minhas alterações. 
- [ ] Testes novos e existentes passam em staging com minhas alterações. 
- [ ] Qualquer dependência dessa alteração já foi realizada (deploy, configuração em todos os ambientes, etc).

2022-04-19 13:21 UTC, cersouza requested changes

2022-04-19 13:21 UTC, cersouza commented on tmpl/funcmaps.go
> +// precision: Quantidade de casas decimais antes da vírgula
Mr @davidsmedeiros, aqui no caso não seria  "Quantidade de casas decimais **depois** da vírgula" ?

2022-04-19 13:21 UTC, cersouza commented on tmpl/funcmaps.go
> +// precision: Quantidade de casas decimais antes da vírgula
Mr @davidsmedeiros, aqui no caso não seria  "Quantidade de casas decimais **depois** da vírgula" ?

2022-04-19 13:21 UTC, cersouza commented on tmpl/funcmaps.go
> +}
@davidsmedeiros, a ideia aqui é pegar a percentagem do `amount` sobre o `totalAmount` ? No caso, então faltou multiplicar o `amount` por 100:
```go
return float64(amount) * 100 / float64(totalAmount)
```

2022-04-19 21:06 UTC, davidsmedeiros commented on tmpl/funcmaps.go
> +// precision: Quantidade de casas decimais antes da vírgula
Seria sim. Eu considerei antes porque admiti que a referência viesse do lado negativo para o positivo.

2022-04-19 21:06 UTC, davidsmedeiros commented on tmpl/funcmaps.go
> +// precision: Quantidade de casas decimais antes da vírgula
Seria sim. Eu considerei antes porque admiti que a referência viesse do lado negativo para o positivo.

2022-04-19 21:08 UTC, davidsmedeiros commented on tmpl/funcmaps.go
> +}
A ideia é essa sim, mas não com a representação que você sugeriu. Você sugeriu a representação percentual, mas o que precisamos é da representação decimal.

2022-04-20 11:57 UTC, davidsmedeiros commented on tmpl/funcmaps.go
> +}
Na documentação está escrito que a variação é de 0.0 a 1.0 para juros e 0.0 a 2.0 para multa. Eu havia considerado esse intervalo como 0 a 100 e 0 a 200, respectivamente. Em conversa com a Isa foi esclarecido que esses intervalos são 0 a 1 e 0 a 2 na representação percentual mesmo, logo sua sugestão está correta.

2022-04-20 20:29 UTC, cersouza requested changes

2022-04-20 20:29 UTC, cersouza commented on stone/stone_test.go
> +func Test_TemplateRequestStone_WhenHasFine_AndWithoutPercentageOnTotal_ParseSuccessful(t *testing.T) {
Nesse caso @davidsmedeiros, usar uma lógica inversa no nome focando no que **terá** na requisição ao invés do que **não terá**. Por exemplo:
 ```go
func Test_TemplateRequestStone_WhenHasFine_WithFineAmount_ParseSuccessful
 ```

2022-04-20 20:29 UTC, cersouza commented on stone/stone_test.go
> +	input := newStubBoletoRequestStone().WithFine(1, 0, 2.0).Build()
@davidsmedeiros, só para melhorar o entendimento do teste, eu sugeriria criar uma variável para nomear os parâmetros do builder. Ex:
```go
boletoDate := 1
percentage := 0
amount := 2.0
input := newStubBoletoRequestStone().WithFine(boletoDate, percentage, amount).Build()
```

O que acha?

2022-04-20 20:29 UTC, cersouza commented on stone/stone_test.go
> +	input := newStubBoletoRequestStone().WithAmountInCents(20000).WithFine(1, 25, 0).Build()
@davidsmedeiros, só para melhorar o entendimento do teste, eu sugeriria criar uma variável para nomear os parâmetros do builder. Ex:
```go
boletoDate := 1
percentage := 25
amount := 0
input := newStubBoletoRequestStone().WithFine(boletoDate, percentage, amount).Build()
```

O que acha?

2022-04-20 20:29 UTC, cersouza commented on stone/stone_test.go
> +	input := newStubBoletoRequestStone().WithInterest(1, 0, 1.0).Build()
@davidsmedeiros, só para melhorar o entendimento do teste, eu sugeriria criar uma variável para nomear os parâmetros do builder. Ex:
```go
boletoDate := 1
percentage := 0
amount := 1.0
input := newStubBoletoRequestStone().WithInterest(boletoDate, percentage, amount).Build()
```

O que acha?

2022-04-20 20:29 UTC, cersouza commented on stone/stone_test.go
> +	input := newStubBoletoRequestStone().WithAmountInCents(20000).WithInterest(1, 25, 0).Build()
@davidsmedeiros, só para melhorar o entendimento do teste, eu sugeriria criar uma variável para nomear os parâmetros do builder. Ex:
```go
boletoDate := 1
percentage := 25
amount := 0
input := newStubBoletoRequestStone().WithInterest(boletoDate, percentage, amount).Build()
```

O que acha?

2022-04-20 20:29 UTC, cersouza commented on stone/stone_test.go
> +func Test_TemplateRequestStone_WhenHasFine_AndWithoutAmountInCents_ParseSuccessful(t *testing.T) {
Nesse caso @davidsmedeiros, usar uma lógica inversa no nome focando no que **terá** na requisição ao invés do que **não terá**. Por exemplo:
 ```go
func Test_TemplateRequestStone_WhenHasFine_WithFinePercent_ParseSuccessful
 ```

2022-04-20 20:35 UTC, cersouza requested changes

2022-04-20 20:35 UTC, cersouza commented on stone/stone_test.go
> +func Test_TemplateRequestStone_WhenHasInterest_AndWithoutPercentageOnTotal_ParseSuccessful(t *testing.T) {
@davidsmedeiros, aqui sugeriria o mesmo do [comentário acima](https://github.com/mundipagg/boleto-api/pull/290/files#r854517553)

2022-04-20 20:35 UTC, cersouza commented on stone/stone_test.go
> +func Test_TemplateRequestStone_WhenHasInterest_AndWithoutAmountInCents_ParseSuccessful(t *testing.T) {
@davidsmedeiros, aqui sugeriria o mesmo do [comentário acima](https://github.com/mundipagg/boleto-api/pull/290/files#r854517553)

2022-04-25 16:22 UTC, davidsmedeiros commented on stone/stone_test.go
> +func Test_TemplateRequestStone_WhenHasFine_AndWithoutPercentageOnTotal_ParseSuccessful(t *testing.T) {
done

2022-04-25 18:06 UTC, cersouza approved these changes
Boa @davidsmedeiros! 

![well-done-dog-p](https://user-images.githubusercontent.com/48000601/165148084-7e6659ac-63df-4921-b859-73628925b963.png)

2022-04-26 12:09 UTC, VictorSamp approved these changes

2022-04-26 17:48 UTC, brunoglm commented on tmpl/funcmaps.go
> +// Truncamento se precision for 2 Ex: 12.3496 -> 12.34
opa, @davidsmedeiros, não deveria virar 12.35 nesse exemplo ? está na documentação que deve pegar o floor ? 😀

2022-04-26 18:18 UTC, brunoglm submitted a review, later dismissed

2022-04-26 18:33 UTC, davidsmedeiros commented on stone/stone_test.go
> +	mock.StartMockService("9201")
@leojasmim Eu tinha entendido que cada método deveria ter uma porta diferente. Inclusive já aconteceu de dois métodos com a mesma porta derem problema no execução local de testes.

2022-05-12 13:46 UTC, VictorSamp submitted a review, later dismissed

2022-05-12 18:00 UTC, vannessasoares commented on api/validator.go
> +		errorResponse.Errors.Append("MP400", "title.fees not available for this bank")
@davidsmedeiros nos testes você chegou a cobrir o `if r != nil && !isBankNumberAcceptRules(bn)`, mas não chegou a cobrir essa condição aqui! acho que a gente pode adicionar os testes pra esse fluxo, o que você acha?

2022-05-12 18:01 UTC, vannessasoares commented on api/validator.go
> +	return b == models.Caixa || b == models.Stone
@davidsmedeiros o mesmo pra essa função aqui! nos testes você cobre só o `isBankNumberAcceptRules`

2022-05-12 18:56 UTC, vannessasoares commented on tmpl/funcmaps.go
> +	return float64(amount) * 100 / float64(totalAmount)
@davidsmedeiros pode adicionar um teste pra o `convertAmountInCentsToPercent` também?

2022-05-12 19:01 UTC, vannessasoares commented on validations/fees.go
> +func ValidateInterest(b interface{}) error {
@davidsmedeiros esses arquivos dentro de `validations` não são testados? tem algum motivo?

2022-05-16 19:03 UTC, brunoglm commented on models/rules.go
> +	MaxDaysToPayPastDue   uint `json:"maxDaysToPayPastDue"`
opa, @davidsmedeiros , existe alguma chance de algum banco usar esse cara com numero inteiro negativo ? no qual precisaria ser type int ? 😀

2022-05-16 19:10 UTC, brunoglm commented on stone/stone_test.go
> +	mock.StartMockService("9201")
quando o runner pega o arquivo, ele roda um teste de cada vez @leojasmim  ?

2022-05-17 14:03 UTC, VictorSamp submitted a review, later dismissed

2022-05-17 14:31 UTC, brunoglm submitted a review, later dismissed

2022-05-22 13:54 UTC, leojasmim commented on stone/stone_test.go
> +	mock.StartMockService("9201")
@brunoglm @davidsmedeiros Ele roda um teste de cada vez... dado que todos os métodos do arquivo de teste utilizam o mock do mesmo serviço não deveria haver problema de todos os métodos utilizarem a mesma porta... O problema é outra arquivo usar a mesma porta pq um método que espera bater no mock de um banco vai bater no mock de outro

2022-05-22 14:12 UTC, leojasmim commented on validations/fees.go
> +func ValidateInterest(b interface{}) error {
@vannessasoares Acabamos criando o de criar o teste dessas validações dentro do arquivo de teste de cada banco.

2022-05-22 14:17 UTC, leojasmim commented on api/validator_test.go
> +	{input: models.Pefisa, expected: false},
@davidsmedeiros Faltou o bradesco 
```suggestion
	{input: models.Pefisa, expected: false},
	{input: models.Bradesco, expected: false},

```

2022-05-22 14:19 UTC, leojasmim commented on api/validator.go
> +	return b == models.Caixa || b == models.Stone
@vannessasoares Mas nesse caso seria apenas o inverso da função... faz sentido testar o **!** dado que ele é da própria linguagem ?

2022-05-22 14:21 UTC, leojasmim commented on api/validator_test.go
> +	{input: models.Pefisa, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.fees not available for this bank"}]}`}},
```suggestion
	{input: models.Pefisa, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.fees not available for this bank"}]}`}},
	{input: models.Bradesco, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.fees not available for this bank"}]}`}},
```

2022-05-22 14:28 UTC, leojasmim commented on api/validator_test.go
> +var validationRulesSuccessParametersV1 = []bankNumberParameter{
@davidsmedeiros Aqui pelo que eu entendi do teste é a validando a rota V1 nos casos de sucesso, logo não tem Rules.. Eu tiraria o nome Rules daqui pq acho q ele acaba confundindo.

2022-05-22 14:33 UTC, leojasmim commented on api/validator_test.go
> +var validationRulesSuccessParametersV1 = []bankNumberParameter{
@davidsmedeiros Aqui pelo que eu entendi do teste é a validando a rota V1 nos casos de sucesso, logo não tem Rules.. Eu tiraria o nome Rules daqui pq acho q ele acaba confundindo.

```suggestion
var validationSuccessParametersV1 = []bankNumberParameter{
```

2022-05-22 14:56 UTC, leojasmim commented on api/validator_test.go
> +		body := test.NewStubBoletoRequest(fact.input).WithExpirationDate(time.Now()).Build()
Para adicionar o Bradesco vc precisa incluir a wallet no BoletoRequest. Ela pode ser inserida para todos os banco pq para esse teste será invariante para os demais bancos.
```suggestion
	body := test.NewStubBoletoRequest(fact.input).WithExpirationDate(time.Now()).WithWallet(25).Build()
```

2022-05-22 15:01 UTC, leojasmim commented on api/validator_test.go
> +	{input: models.Caixa, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.rules not available in this version"}]}`}},
@davidsmedeiros Aproveitaria os parameters para incluir os demais bancos no teste
```suggestion
	{input: models.Caixa, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.rules not available in this version"}]}`}},
	{input: models.BancoDoBrasil, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.rules not available in this version"}]}`}},
	{input: models.Bradesco, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.rules not available in this version"}]}`}},
	{input: models.Citibank, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.rules not available in this version"}]}`}},
	{input: models.Itau, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.rules not available in this version"}]}`}},
	{input: models.JPMorgan, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.rules not available in this version"}]}`}},
	{input: models.Pefisa, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.rules not available in this version"}]}`}},
	{input: models.Santander, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.rules not available in this version"}]}`}},
```

2022-05-22 15:10 UTC, leojasmim commented on api/validator.go
>  	rules := getBoletoFromContext(c).Title.Rules
```suggestion
	title := getBoletoFromContext(c).Title
```

2022-05-22 15:13 UTC, leojasmim commented on api/validator.go
> +	f := getBoletoFromContext(c).Title.Fees
Melhor usar o _**title**_ e seus métodos de validação.
```suggestion
	t := getBoletoFromContext(c).Title
```

2022-05-22 15:13 UTC, leojasmim commented on api/validator.go
> +	if r != nil && !isBankNumberAcceptRules(bn) {
```suggestion
	if t.HasRules() && !isBankNumberAcceptRules(bn) {
```

2022-05-22 15:14 UTC, leojasmim commented on api/validator.go
> +	if f != nil && !isBankNumberAcceptFees(bn) {
```suggestion
	t.HasFees() && !isBankNumberAcceptFees(bn)
```

2022-05-22 15:33 UTC, leojasmim commented on models/rules.go
> +	MaxDaysToPayPastDue   uint `json:"maxDaysToPayPastDue"`
@brunoglm Acredito que não dado que a semântica do campo é dias após o vencimento, logo o menor valor esperado para o campo é o 0.

2022-05-22 15:39 UTC, leojasmim reviewed
Deixei umas observações

2022-05-23 19:27 UTC, davidsmedeiros commented on api/validator.go
> +	f := getBoletoFromContext(c).Title.Fees
done

2022-05-23 19:27 UTC, davidsmedeiros commented on api/validator.go
> +	if r != nil && !isBankNumberAcceptRules(bn) {
done

2022-05-23 19:27 UTC, davidsmedeiros commented on api/validator.go
> +	if f != nil && !isBankNumberAcceptFees(bn) {
done

2022-05-23 19:27 UTC, davidsmedeiros commented on api/validator_test.go
> +	{input: models.Pefisa, expected: false},
done

2022-05-23 19:27 UTC, davidsmedeiros commented on api/validator_test.go
> +	{input: models.Pefisa, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.fees not available for this bank"}]}`}},
done

2022-05-23 19:27 UTC, davidsmedeiros commented on api/validator_test.go
> +var validationRulesSuccessParametersV1 = []bankNumberParameter{
done

2022-05-23 19:27 UTC, davidsmedeiros commented on api/validator_test.go
> +	{input: models.Caixa, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.rules not available in this version"}]}`}},
done

2022-05-23 19:27 UTC, davidsmedeiros commented on api/validator_test.go
> +		body := test.NewStubBoletoRequest(fact.input).WithExpirationDate(time.Now()).Build()
done

2022-05-23 19:27 UTC, davidsmedeiros commented on stone/stone_test.go
> +	mock.StartMockService("9201")
done

2022-05-23 19:52 UTC, brunoglm submitted a review, later dismissed

2022-05-23 19:59 UTC, VictorSamp submitted a review, later dismissed

2022-05-24 17:28 UTC, cersouza submitted a review, later dismissed
![image](https://user-images.githubusercontent.com/48000601/170096275-c19707ac-f7e1-4f5c-8914-912a11b22490.png)

2022-05-25 14:45 UTC, vannessasoares commented on api/validator.go
> +	return b == models.Caixa || b == models.Stone
@leojasmim acho que não entendi! a ideia seria testar essa função do mesmo jeito que ele já tinha testado com Rules. Mas acho que você tava falando da condição anterior, na linha 45, né?! Se foi isso, a ideia era adicionar um teste que passasse pela condição e batesse no erro, como ele já tinha feito pra Rules também ☺️

2022-05-26 17:10 UTC, cersouza submitted a review, later dismissed

2022-06-02 12:10 UTC, brunoglm approved these changes

2022-06-02 17:25 UTC, leojasmim commented on api/validator_test.go
> +	{input: models.Caixa, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.rules not available in this version"}]}`}},
@davidsmedeiros acabou ficando caixa 2 vezes

2022-06-02 17:27 UTC, leojasmim commented on stone/contracts.go
> +        ,"fine": {
@davidsmedeiros Boa a da vírgula aqui

2022-06-02 17:32 UTC, leojasmim approved these changes

2022-06-02 18:45 UTC, davidsmedeiros commented on api/validator_test.go
> +	{input: models.Caixa, expected: bankNumberExpectedParameter{code: 400, message: `{"errors":[{"code":"MP400","message":"title.rules not available in this version"}]}`}},
done

2022-06-03 12:03 UTC, leojasmim approved these changes

2022-06-07 11:40 UTC, VictorSamp approved these changes

2022-06-07 12:43 UTC, merged