feat: send the document number on request to banco do brasil
mundipagg/boleto-api pull request #294
Opened 2022-06-23 14:54 UTC by brunoglm

# Descrição

### Tarefa [CA-427](https://mundipagg.atlassian.net/secure/RapidBoard.jspa?rapidView=76&projectKey=CA&modal=detail&selectedIssue=CA-427) 

Por favor, inclua um resumo da alteração e qual problema foi corrigido ou feature foi adicionada. Inclua também motivação relevante e contexto. Liste todas as dependências necessárias para essa mudança.

### Tipos de alterações

- [ ] Correção de bug 
- [ ] Nova feature 
- [ ] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes

Por favor, descreva os testes que você executou para verificar suas alterações. Forneça instruções necessárias para que seja possível reproduzir os testes e evidências de suas execuções com sucesso.
Se possível, anexe na tarefa a coleção de requisições executadas no teste. (Nesse caso adicione o link abaixo)

### Coleção de Testes [Download](https://www.getpostman.com/collections/83ff1739e979805b1ff6)

### Teste A

Descreva cenário do teste realizado com instruções necessárias para reprodução e evidência de sua execução com sucesso.
Utilize código e/ou imagens (prints) para ilustrar seus teste.

```
{
  "Description": "JSON utilizado no Request do Teste A"
}
```

### Teste B

Descreva cenário do teste realizado com instruções necessárias para reprodução e evidência de sua execução com sucesso.
Utilize código e/ou imagens (prints) para ilustrar seus teste.

```
{
  "Description": "JSON utilizado no Request do Teste B"
}
```

## Checklist

- [ ] Associei corretamente a Tarefa do Board ao Pull Request.
- [ ] Meu código segue as diretrizes desse projeto.
- [ ] Eu revisei meu próprio código.
- [ ] Eu comentei meu código em áreas particulares de difícil compreensão.
- [ ] Eu atualizei a documentação de acordo com as mudanças realizadas.
- [ ] Meu código não gerou novos warnings.
- [ ] Eu adicionei testes que provam que minha correção é efetiva ou que a nova feature funciona.
- [ ] Testes novos e existentes passam localmente com minhas alterações. 
- [ ] Testes novos e existentes passam em staging com minhas alterações. 
- [ ] Qualquer dependência dessa alteração já foi realizada (deploy, configuração em todos os ambientes, etc).

2022-06-23 16:29 UTC, VictorSamp approved these changes

2022-06-24 13:00 UTC, VictorSamp approved these changes

2022-06-27 20:52 UTC, cersouza requested changes
Boa @brunoglm, deixe um comment só 🔍

2022-06-27 20:52 UTC, cersouza commented on bb/validations.go
> +			return models.NewErrorResponse("MP400", "o campo documentNumber ultrapassou o limite permitido de caracteres")
@brunoglm, será que nesse caso, para facilitar o entendimento do erro pelo cliente deixar explícito o limite permitido ? Ex: "o campo documentNumber ultrapassou o limite permitido de **15** caracteres"

2022-06-27 21:11 UTC, davidsmedeiros approved these changes

2022-06-27 21:11 UTC, davidsmedeiros commented on bb/validations_test.go
> +		Input:    newStubBoletoRequestBB().WithTitle(models.Title{DocumentNumber: "lojas-16-digitos"}).Build(),
O que acontece se for 0 caracteres?

2022-06-28 13:16 UTC, brunoglm commented on bb/validations.go
> +			return models.NewErrorResponse("MP400", "o campo documentNumber ultrapassou o limite permitido de caracteres")
Done 😀

2022-06-28 13:17 UTC, brunoglm commented on bb/validations.go
> +			return models.NewErrorResponse("MP400", "o campo documentNumber ultrapassou o limite permitido de caracteres")
Done 😀

2022-06-28 13:17 UTC, brunoglm commented on bb/validations_test.go
> +		Expected: models.NewErrorResponse("MP400", "o campo documentNumber ultrapassou o limite permitido de caracteres"),
Done 😀

2022-06-28 14:38 UTC, VictorSamp submitted a review, later dismissed

2022-06-28 15:38 UTC, cersouza reviewed
Boa @brunoglm ! 🚀

2022-06-28 17:13 UTC, cersouza submitted a review, later dismissed

2022-06-28 17:51 UTC, leojasmim commented on bb/validations.go
> +			message := fmt.Sprintf("O campo documentNumber ultrapassou o limite permitido de %d caracteres", maxAllowedLength)
@brunoglm Adicionaria a palavra `título` porque tem vários DocumentNumber no contrato (Buye, Recipient) ... Só pra ficar mais claro
```suggestion
			message := fmt.Sprintf("O campo documentNumber do título ultrapassou o limite permitido de %d caracteres", maxAllowedLength)
```

2022-06-28 17:51 UTC, leojasmim submitted a review, later dismissed

2022-06-28 19:36 UTC, brunoglm commented on bb/validations.go
> +			message := fmt.Sprintf("O campo documentNumber ultrapassou o limite permitido de %d caracteres", maxAllowedLength)
Done 😀

2022-06-28 19:39 UTC, leojasmim reviewed
Boa @brunoglm ... Vamos só aguardar o retorno do BB.

2022-07-01 18:02 UTC, leojasmim approved these changes

2022-07-06 14:55 UTC, merged