[BPROC-655] change default value for maxDaysToPayPastDue
mundipagg/boleto-api pull request #299
Opened 2022-09-27 13:49 UTC by lucasarantespagarme

# Descrição

### Tarefa [BPROC-655](https://mundipagg.atlassian.net/browse/BPROC-655) 

Atualmente o prazo de baixa para Stone está com 60 dias após a data de vencimento. Nos modelos de negócio que temos atualmente temos que recusar um pagamento após a data de vencimento, Para isso devemos alterar o prazo de baixa para o menor dia possível após a data de vencimento que para a Stone seria 1.

Esse PR realiza essa mudança alterando o valor do campo de prazo de baixa da Stone na boleto-api para 1.

### Tipos de alterações

- [ ] Correção de bug 
- [ ] Nova feature 
- [x] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes

Foram criados 2 testes unitários para validar os 2 cenários da alteração (com e sem o MaxDaysToPayPastDue), além disso todos os testes existentes continuam passando.

![image](https://user-images.githubusercontent.com/113469418/192543490-b90345f0-1455-490a-8dfb-ba6efc25b1d4.png)

## Checklist

- [x] Associei corretamente a Tarefa do Board ao Pull Request.
- [x] Meu código segue as diretrizes desse projeto.
- [x] Eu revisei meu próprio código.
- [x] Eu comentei meu código em áreas particulares de difícil compreensão.
- [x] Eu atualizei a documentação de acordo com as mudanças realizadas.
- [x] Meu código não gerou novos warnings.
- [x] Eu adicionei testes que provam que minha correção é efetiva ou que a nova feature funciona.
- [x] Testes novos e existentes passam localmente com minhas alterações. 
- [ ] Testes novos e existentes passam em staging com minhas alterações. 
- [x] Qualquer dependência dessa alteração já foi realizada (deploy, configuração em todos os ambientes, etc).

2022-09-27 14:27 UTC, JeanCigoli commented on stone/stone_test.go
> +func Test_TemplateRequestStone_WhenHasMaxDaysToPayPastDue_ShouldValidadate(t *testing.T) {
Opa! No nome do teste a parte `ShouldValidadate` fiquei meio confuso, escrevendo separado seria **should valid a date**?

2022-09-27 14:33 UTC, lucasarantespagarme commented on stone/stone_test.go
> +func Test_TemplateRequestStone_WhenHasntMaxDaysToPayPastDue_ShouldUseDefaultValue(t *testing.T) {
boa, vou realizar a alteração

2022-09-27 14:36 UTC, lucasarantespagarme commented on stone/stone_test.go
> +func Test_TemplateRequestStone_WhenHasntMaxDaysToPayPastDue_ShouldUseDefaultValue(t *testing.T) {
boa! atualizado :)

2022-09-27 14:36 UTC, leojasmim commented on stone/stone_test.go
> +func Test_TemplateRequestStone_WhenHasMaxDaysToPayPastDue_ShouldValidadate(t *testing.T) {
👍

2022-09-27 14:36 UTC, lucasarantespagarme commented on stone/stone_test.go
> +func Test_TemplateRequestStone_WhenHasMaxDaysToPayPastDue_ShouldValidadate(t *testing.T) {
boa! atualizado :)

2022-09-27 14:36 UTC, lucasarantespagarme commented on stone/stone_test.go
> +func Test_TemplateRequestStone_WhenHasMaxDaysToPayPastDue_ShouldValidadate(t *testing.T) {
realmente, fiz uma alteração aqui que resolve isso, valeu :)

2022-09-27 14:42 UTC, JeanCigoli approved these changes
Boa 🚀

2022-09-27 14:44 UTC, brunoglm approved these changes
Boaa @lucasarantespagarme 🚀

2022-09-27 14:47 UTC, leojasmim commented on stone/stub.go
> +func (s *stubBoletoRequestStone) WithTitle(title models.Title) *stubBoletoRequestStone {
@lucasarantespagarme Não sei se vc reparou mas o objeto default já traz um title com o expirationDate configurado. Sugiro que, ao invés de adicionar uma `WithTitle` incluir uma função mais específica, por exemplo, `WithMaxDaysToPayPastDue` que recebe como parâmetro apenas a quantidade de dias e inclua no title default já existente o no de Rules com o valor passado. Assim o teste ficará menos verboso.

2022-09-27 14:49 UTC, leojasmim commented on stone/stone_test.go
> +			MaxDaysToPayPastDue: 5,
@lucasarantespagarme Aqui o `5` poderia estar em uma variável `expectedMaxDaysToPayPastDue` e assim poderia ser utilizada tbm na linha 205 para gerar a data esperada. Assim caso seja necessário alterar o valor do teste a alteração estará vinculada a um único ponto.

2022-09-27 14:50 UTC, leojasmim requested changes
@lucasarantespagarme Muito bom !!! Deixei apenas algumas sugestões para vc dar uma analisada.

2022-09-27 15:19 UTC, lucasarantespagarme commented on stone/stub.go
> +func (s *stubBoletoRequestStone) WithTitle(title models.Title) *stubBoletoRequestStone {
@leojasmim excelente visão, realizei a melhoria, valeu

2022-09-27 15:26 UTC, lucasarantespagarme commented on stone/stone_test.go
> +			MaxDaysToPayPastDue: 5,
boa, feito ! :)

2022-09-27 16:34 UTC, brunoglm approved these changes

2022-09-27 17:36 UTC, JeanCigoli approved these changes

2022-09-28 12:41 UTC, davidsmedeiros approved these changes

2022-09-28 13:54 UTC, cersouza approved these changes
Boa mano @lucasarantespagarme 🚀 🚀

2022-10-05 12:06 UTC, merged