chore: added catalog-info
mundipagg/boleto-api pull request #304
Opened 2022-12-20 17:10 UTC by davidsmedeiros

# Descrição

### Tarefa [CA-427](https://mundipagg.atlassian.net/secure/RapidBoard.jspa?rapidView=76&projectKey=CA&modal=detail&selectedIssue=CA-427) 

Por favor, inclua um resumo da alteração e qual problema foi corrigido ou feature foi adicionada. Inclua também motivação relevante e contexto. Liste todas as dependências necessárias para essa mudança.

### Tipos de alterações

- [ ] Correção de bug 
- [ ] Nova feature 
- [ ] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes

Por favor, descreva os testes que você executou para verificar suas alterações. Forneça instruções necessárias para que seja possível reproduzir os testes e evidências de suas execuções com sucesso.
Se possível, anexe na tarefa a coleção de requisições executadas no teste. (Nesse caso adicione o link abaixo)

### Coleção de Testes [Download](https://www.getpostman.com/collections/83ff1739e979805b1ff6)

### Teste A

Descreva cenário do teste realizado com instruções necessárias para reprodução e evidência de sua execução com sucesso.
Utilize código e/ou imagens (prints) para ilustrar seus teste.

```
{
  "Description": "JSON utilizado no Request do Teste A"
}
```

### Teste B

Descreva cenário do teste realizado com instruções necessárias para reprodução e evidência de sua execução com sucesso.
Utilize código e/ou imagens (prints) para ilustrar seus teste.

```
{
  "Description": "JSON utilizado no Request do Teste B"
}
```

## Checklist

- [ ] Associei corretamente a Tarefa do Board ao Pull Request.
- [ ] Meu código segue as diretrizes desse projeto.
- [ ] Eu revisei meu próprio código.
- [ ] Eu comentei meu código em áreas particulares de difícil compreensão.
- [ ] Eu atualizei a documentação de acordo com as mudanças realizadas.
- [ ] Meu código não gerou novos warnings.
- [ ] Eu adicionei testes que provam que minha correção é efetiva ou que a nova feature funciona.
- [ ] Testes novos e existentes passam localmente com minhas alterações. 
- [ ] Testes novos e existentes passam em staging com minhas alterações. 
- [ ] Qualquer dependência dessa alteração já foi realizada (deploy, configuração em todos os ambientes, etc).

2022-12-20 18:14 UTC, cersouza requested changes
Mano @davidsmedeiros, boa, mesmo que iniciais essas docs vão ajudar muito ! 🗿   

Deixei alguns comentários de possíveis correções...

2022-12-20 18:14 UTC, cersouza commented on catalog-info.yaml
> +  namespace: mundipagg | pagarme
@davidsmedeiros, acredito que aqui deveria ser uma das duas opções, no caso, acredito que seria mundipagg por estar na infra dela.

2022-12-20 18:14 UTC, cersouza commented on catalog-info.yaml
> +  system: mundipagg/boleto-api
@davidsmedeiros, acredito que por esse já ser do tipo `System`, não é necessário especificar o system.

2022-12-20 18:14 UTC, cersouza commented on catalog-info.yaml
> +    owner: pagarme/processing-banks
@davidsmedeiros, segundo a [doc](https://mundipagg.atlassian.net/l/cp/TmAPbk1k), acho que por enquanto não temos mais essa chave `monitoring` (talvez deixar ela pode dar ruim). E a chave `owner` agora fica no mesmo nível das chaves `type` e `lifecycle`.

2022-12-20 18:14 UTC, cersouza commented on catalog-info.yaml
> +  name: mongo
@davidsmedeiros, acho que vale (se essa for uma informação que possa estar aberta, colocar o nome do Banco de Dados)

2022-12-20 18:14 UTC, cersouza commented on catalog-info.yaml
> +    stone.co/pci: "true"
@davidsmedeiros, o DB da Boleto-API é PCI ? Se sim a própria boleto-api também seria não ?

2022-12-20 18:24 UTC, JeanCigoli commented on catalog-info.yaml
> +  title: Documentação técnica
Acho que esse title pode ser outro, o que acha?
```suggestion
  title: boleto-api-server
```

2022-12-20 18:28 UTC, JeanCigoli commented on catalog-info.yaml
> +  name: mongo
E se puder colocar, talvez deixar o nome no title

2022-12-20 18:31 UTC, JeanCigoli approved these changes

2022-12-21 17:12 UTC, davidsmedeiros commented on catalog-info.yaml
> +    stone.co/pci: "true"
não sei dizer

2022-12-21 18:32 UTC, brunoglm commented on catalog-info.yaml
> +  title: boleto-api
```suggestion
  title: Boleto-api
```

2022-12-21 18:47 UTC, brunoglm commented on catalog-info.yaml
> +  description: Gateway de registro online de transações do meio de pagamento de boleto.
Aqui, acho que seria algo nessa linha 😀 
```suggestion
  description: Servidor responsável por receber requests http.
```

2022-12-21 19:11 UTC, brunoglm commented on catalog-info.yaml
> +  name: mongo
Esse é o que foi colocado na super boleto e sem description. Acho que da pra gente ver um padrão e deixar os dois parecidos, o que acham ? 😀 

name: live-superbowleto
  title: Superbowleto Database

2022-12-21 19:13 UTC, brunoglm commented on catalog-info.yaml
> +  description: Storage de armazenamento de certificados.
Algo nessa linha eu acho 😀 
```suggestion
  description: Storage de armazenamento de certificados e segundo nível de resiliência de registro de boletos.
```

2022-12-21 19:16 UTC, brunoglm commented on catalog-info.yaml
> +  owner: pagarme/processing-banks
@davidsmedeiros , tá faltando uma linha em branco no final do arquivo 😀

2022-12-22 12:46 UTC, cersouza commented on catalog-info.yaml
> +  title: boleto-api
@brunoglm algum motivo especial para deixar a primeira letra maisucula?

2022-12-22 12:49 UTC, cersouza commented on catalog-info.yaml
>    name: boleto-api
@davidsmedeiros, não sei se gera conflito com o nome do System, mas sugeriria deixar o nome aqui como `boleto-api-server` também !

2022-12-27 19:57 UTC, JeanCigoli submitted a review, later dismissed

2022-12-29 15:56 UTC, cersouza requested changes

2022-12-29 15:56 UTC, cersouza commented on catalog-info.yaml
> +  name:  boleto-api-server
@davidsmedeiros, aqui sugeriria deixar o name do System só `boleto-api` para seguir o padrão dos repositórios

2022-12-29 18:41 UTC, kayquecoelho approved these changes

2022-12-29 19:01 UTC, brunoglm submitted a review, later dismissed

2022-12-30 14:01 UTC, cersouza approved these changes

2022-12-30 14:31 UTC, cersouza requested changes
Mano @kayquecoelho, deixei alguns comentários só na preocupação de a doc não quebrar no Backstage 👨🏾‍🚀

2022-12-30 14:31 UTC, cersouza commented on catalog-info.yaml
> +    owner: pagarme/processing-banks
@kayquecoelho, acredito que vamos precisar ajustar esse ponto aqui. Seria remover a chave `monitoring` e deixar a chave `owner` no mesmo nível de `type` e `lifecycle`.

2022-12-30 14:31 UTC, cersouza commented on catalog-info.yaml
> +  name: mongo
@kayquecoelho, seguindo a [Doc do Backstage](https://backstage.io/docs/features/software-catalog/descriptor-format#name-required) o atributo `name` precisa ser único por `kind` e `namespace`. Talvez não seja ideal, mas para não gerar conflito sugeriria deixar o name como `boleto-api-mongo` 

E faltou adicionarmos a chave `namespace: mundipagg`. Pela a [doc](https://mundipagg.atlassian.net/wiki/spaces/PM/pages/5791089758/Cat+logo+-+Backstage) ela é obrigatória.

2022-12-30 14:31 UTC, cersouza commented on catalog-info.yaml
> +  name: boleto-recovery-queue
@kayquecoelho, faltou adicionarmos a chave `namespace: mundipagg`. Pela a [doc](https://mundipagg.atlassian.net/wiki/spaces/PM/pages/5791089758/Cat+logo+-+Backstage) ela é obrigatória.

2022-12-30 14:31 UTC, cersouza commented on catalog-info.yaml
> +  type: queue
@kayquecoelho, nesse caso, acredito que o type seria `backend`, para seguir o padrão das outras filas que declaramos nos outros projetos.

2022-12-30 14:31 UTC, cersouza commented on catalog-info.yaml
> +  name: Blob
@kayquecoelho, seguindo a [Doc do Backstage](https://backstage.io/docs/features/software-catalog/descriptor-format#name-required) o atributo `name` precisa ser único por `kind` e `namespace`. Talvez não seja ideal, mas para não gerar conflito sugeriria deixar o name como `boleto-api-blob` 

E faltou adicionarmos a chave `namespace: mundipagg`. Pela a [doc](https://mundipagg.atlassian.net/wiki/spaces/PM/pages/5791089758/Cat+logo+-+Backstage) ela é obrigatória.

2022-12-30 14:31 UTC, cersouza commented on catalog-info.yaml
> +  type: queue
@kayquecoelho, nesse caso, acredito que o type seria `backend`.

2022-12-30 14:31 UTC, cersouza commented on catalog-info.yaml
> +  name: Vault
@kayquecoelho, seguindo a [Doc do Backstage](https://backstage.io/docs/features/software-catalog/descriptor-format#name-required) o atributo `name` precisa ser único por `kind` e `namespace`. Talvez não seja ideal, mas para não gerar conflito sugeriria deixar o name como `boleto-api-vault` 

E faltou adicionarmos a chave `namespace: mundipagg`. Pela a [doc](https://mundipagg.atlassian.net/wiki/spaces/PM/pages/5791089758/Cat+logo+-+Backstage) ela é obrigatória.

2022-12-30 14:31 UTC, cersouza commented on catalog-info.yaml
> +  type: queue
@kayquecoelho, nesse caso, acredito que o type seria `backend`.

2022-12-30 14:31 UTC, cersouza commented on catalog-info.yaml
> +  namespace: pagarme
@kayquecoelho, acredito que o namespace aqui seria `mundipagg` mesmo

2022-12-30 14:31 UTC, cersouza commented on catalog-info.yaml
> +    pagar.me/cd: azure-devops
@kayquecoelho, nesse caso por ser repositório acredito que podemos rever o CI/CD

2022-12-30 15:02 UTC, kayquecoelho commented on catalog-info.yaml
> +  type: queue
@cersouza , nesse caso eu mantive o type como queue pq é de fato uma fila de resiliência fechou?

2022-12-30 15:14 UTC, cersouza approved these changes

2022-12-30 16:37 UTC, kayquecoelho approved these changes

2022-12-30 18:03 UTC, merged